import Link from "next/link"
import { notFound } from "next/navigation"
import {
  addSprintDependencyAction,
  addSprintOutcomeAction,
  addSprintWorkAction,
  closeSprintAction,
  decideSprintOutcomeAction,
  saveSprintAction,
} from "../../../../actions"
import { WorkspaceError } from "../../../../../src/domain/errors"
import { WorkspaceRepository } from "../../../../../src/integration/filesystem/workspace-repository"
import { toSprintDetailViewModel, toWorkReferenceOptionViewModel } from "../../../../../src/ui/presenters/adaptive-work-presenter"

export default async function SprintDetailPage({ params }: { params: Promise<{ sprintId: string }> }) {
  const { sprintId } = await params
  const repository = await WorkspaceRepository.create()
  let sprint
  try { sprint = await repository.getSprint(sprintId) } catch (error) { if (error instanceof WorkspaceError && error.code === "NOT_FOUND") notFound(); throw error }
  const projects = (await repository.discoverProjects()).filter((project) => project.initialized && !project.corrupted)
  const collections = await Promise.all(projects.map(async (project) => ({ project, items: await repository.listWorkItems(project.id), requests: await repository.listAgentRequests(project.id), roadmap: await repository.getRoadmap(project.id) })))
  const workItems = collections.flatMap((collection) => collection.items)
  const requests = collections.flatMap((collection) => collection.requests)
  const workOptions = collections.flatMap(({ project, items }) => items.filter((item) => item.productStatus !== "archived").map((item) => toWorkReferenceOptionViewModel(item, project.displayName)))
  const view = toSprintDetailViewModel(sprint, workItems, requests)
  const nextSprints = (await repository.listSprints()).filter((candidate) => candidate.id !== sprintId && candidate.status === "planning")
  return (
    <>
      <header className="page-header compact-header"><div><p className="eyebrow">{view.periodLabel}</p><h1>{view.name}</h1><p>{view.intent}</p></div><span className={`status-chip ${view.status}`}><i />{view.status}</span></header>
      <section className="sprint-intent-strip" aria-label="Estado operacional"><div><strong>{view.validatedOutcomes}/{view.outcomeCount}</strong><span>outcomes validados</span></div><div><strong>{view.wipLabel}</strong><span>WIP ativo</span></div><div><strong>{view.reviewCount}</strong><span>fila de review</span></div><div><strong>{view.validationCount}</strong><span>fila de validação</span></div><div><strong>{view.blockedCount}</strong><span>bloqueios</span></div><div><strong>{view.confidenceLabel}</strong><span>confiança</span></div></section>
      <div className="sprint-detail-grid">
        <div className="sprint-flow">
          <section className="sprint-section"><header><div><p className="eyebrow">Compromisso</p><h2>Outcomes</h2></div><span>{view.outcomes.length}</span></header>
            {view.outcomes.map((outcome) => <article className="outcome-row" key={outcome.id}><div><strong>{outcome.title}</strong><small>{outcome.refLabel}</small></div><span className={`status-chip ${outcome.result ? "success" : "planned"}`}><i />{outcome.result ?? "aguardando decisão"}</span>{!outcome.result && view.status !== "completed" ? <form action={decideSprintOutcomeAction} className="outcome-decision"><input name="sprintId" type="hidden" value={view.id} /><input name="commitmentId" type="hidden" value={outcome.id} /><input name="revision" type="hidden" value={view.revision} /><select name="result" required><option value="validated">Validado</option><option value="partial">Parcial</option><option value="not_met">Não atingido</option><option value="dropped">Removido</option><option value="carried_over">Carry-over</option></select><input name="resultSummary" placeholder="Decisão e aprendizado" required /><textarea name="evidenceRefs" placeholder="Evidências, uma por linha" rows={2} /><button className="button" type="submit">Registrar decisão</button></form> : outcome.resultSummary ? <p>{outcome.resultSummary}</p> : null}</article>)}
            {!view.outcomes.length ? <div className="empty-state compact-empty"><strong>Nenhum outcome comprometido.</strong><span>Adicione um WorkItem Outcome ou Initiative.</span></div> : null}
          </section>
          <section className="sprint-section"><header><div><p className="eyebrow">Fluxo real</p><h2>Trabalho → Review → Validação</h2></div><span>{view.work.length}</span></header>
            <div className="sprint-work-head"><span>Trabalho</span><span>Execução</span><span>Review</span><span>Validação</span></div>
            {view.work.map((item) => <Link className="sprint-work-row" href={item.href} key={`${item.projectId}:${item.workItemId}`}><span><strong>{item.title}</strong><small>{item.projectLabel} · produto {item.status}</small></span><span>{item.executionLabel}</span><span>{item.reviewLabel}</span><span>{item.validationLabel}</span></Link>)}
            {!view.work.length ? <div className="empty-state compact-empty"><strong>Nenhum trabalho comprometido.</strong><span>Relacione trabalho a um outcome para tornar o progresso explicável.</span></div> : null}
          </section>
          {view.dependencies.length ? <section className="sprint-section"><header><div><p className="eyebrow">Coordenação transversal</p><h2>Dependências entre projetos</h2></div><span>{view.dependencies.length}</span></header>{view.dependencies.map((dependency) => <article className="dependency-line" key={dependency.id}><div><strong>{dependency.summary}</strong><small>{dependency.fromLabel} → {dependency.toLabel}</small></div></article>)}</section> : null}
          {view.closure ? <section className="sprint-section memory-panel"><p className="eyebrow">Memória permanente</p><h2>Encerramento registrado</h2><p>{view.closure.summary}</p><code>{view.closure.memoryDocumentRef}</code>{view.closure.nextSprintId ? <p>Carry-over → <Link href={`/work/sprints/${view.closure.nextSprintId}`}>{view.closure.nextSprintId}</Link></p> : null}</section> : null}
        </div>
        <aside className="adaptive-inspector sprint-controls">
          <details open><summary>Intenção e capacidade</summary><form action={saveSprintAction} className="adaptive-form"><input name="sprintId" type="hidden" value={view.id} /><input name="revision" type="hidden" value={view.revision} /><label>Nome<input defaultValue={view.name} name="name" required /></label><label>Intent<textarea defaultValue={view.intent} name="intent" required rows={3} /></label><div className="form-grid"><label>Início<input defaultValue={view.startDate} name="startDate" type="date" /></label><label>Fim<input defaultValue={view.endDate} name="endDate" type="date" /></label><label>Estado<select defaultValue={view.status} name="status"><option value="planning">Planejamento</option><option value="active">Ativa</option><option value="validation">Validação</option><option value="cancelled">Cancelada</option></select></label><label>WIP<input defaultValue={view.wipLimit} min="1" name="wipLimit" type="number" /></label><label>Confiança<input defaultValue={view.confidence ?? ""} max="5" min="1" name="confidence" type="number" /></label></div><label>Justificativa de override<input defaultValue={view.wipOverrideReason} name="wipOverrideReason" /></label><label>Justificativa da confiança<textarea defaultValue={view.confidenceRationale} name="confidenceRationale" rows={2} /></label><label>Riscos<textarea defaultValue={view.risksText} name="risks" rows={3} /></label><button className="button" type="submit">Salvar sprint</button></form></details>
          {view.status !== "completed" ? <details><summary>Dependência entre projetos</summary><form action={addSprintDependencyAction} className="adaptive-form"><input name="sprintId" type="hidden" value={view.id} /><input name="revision" type="hidden" value={view.revision} /><label>Resumo<input name="summary" placeholder="O que precisa acontecer primeiro?" required /></label><label>Pré-requisito<select name="fromRef" required><option value="">Escolha o trabalho de origem</option>{workOptions.map((option) => <option key={`from:${option.value}`} value={option.value}>{option.label}</option>)}</select></label><label>Trabalho dependente<select name="toRef" required><option value="">Escolha o trabalho dependente</option>{workOptions.map((option) => <option key={`to:${option.value}`} value={option.value}>{option.label}</option>)}</select></label><button className="button" type="submit">Registrar dependência</button></form></details> : null}
          {view.status !== "completed" ? <><details><summary>Comprometer outcome</summary><form action={addSprintOutcomeAction} className="adaptive-form"><input name="sprintId" type="hidden" value={view.id} /><input name="revision" type="hidden" value={view.revision} /><label>Fonte<select name="referenceKind"><option value="work_item_outcome">WorkItem Outcome</option><option value="roadmap_initiative">Roadmap Initiative</option></select></label><label>Projeto<select name="projectId">{projects.map((project) => <option key={project.id} value={project.id}>{project.displayName}</option>)}</select></label><label>ID do Outcome ou Initiative<input name="referenceId" required /></label><button className="button" type="submit">Adicionar compromisso</button></form></details><details><summary>Adicionar trabalho</summary><form action={addSprintWorkAction} className="adaptive-form"><input name="sprintId" type="hidden" value={view.id} /><input name="revision" type="hidden" value={view.revision} /><label>Outcome<select name="outcomeCommitmentId" required>{view.outcomes.map((outcome) => <option key={outcome.id} value={outcome.id}>{outcome.title}</option>)}</select></label><label>Projeto<select name="projectId">{projects.map((project) => <option key={project.id} value={project.id}>{project.displayName}</option>)}</select></label><label>ID do work item<input name="workItemId" required /></label><label>Execução<select name="executionMode"><option value="human">Humana</option><option value="codex">Codex</option><option value="agent">Agente</option><option value="paired">Pareada</option></select></label><button className="button" disabled={!view.outcomes.length} type="submit">Adicionar à sprint</button></form></details><details><summary>Encerrar e memorizar</summary><form action={closeSprintAction} className="adaptive-form"><input name="sprintId" type="hidden" value={view.id} /><input name="revision" type="hidden" value={view.revision} /><p className="adaptive-lede">Mova a sprint para Validação e registre uma decisão para cada outcome antes de encerrar.</p><label>Resumo final<textarea name="summary" placeholder="Resultado, decisões e aprendizados permanentes" required rows={5} /></label><label>Sprint seguinte para carry-over<select name="nextSprintId"><option value="">Sem carry-over</option>{nextSprints.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label><button className="button primary" disabled={view.status !== "validation" || view.outcomes.some((outcome) => !outcome.result)} type="submit">Encerrar sprint</button></form></details></> : null}
        </aside>
      </div>
    </>
  )
}
