"use client"
import { useState, type FormEvent } from "react"
import type { CatalogEditorProductViewModel } from "./presenters/catalog.presenter"
type Category = { readonly id: string; readonly name: string }
const EMPTY_VARIANT = { name: "Padrão", sku: "", price: "" }
export function CatalogEditor({ categories: initialCategories, product }: { readonly categories: readonly Category[]; readonly product?: CatalogEditorProductViewModel }) {
  const [categories, setCategories] = useState([...initialCategories]); const [categoryName, setCategoryName] = useState("")
  const [name, setName] = useState(product?.name ?? ""); const [slug, setSlug] = useState(product?.slug ?? ""); const [description, setDescription] = useState(product?.description ?? "")
  const [categoryId, setCategoryId] = useState(product?.categoryId ?? ""); const [type, setType] = useState<"SIMPLE" | "CONFIGURABLE">(product?.type ?? "SIMPLE")
  const [status, setStatus] = useState<"DRAFT" | "ACTIVE" | "ARCHIVED">(product?.status ?? "DRAFT"); const [variants, setVariants] = useState(product?.variants.map((item) => ({ ...item })) ?? [{ ...EMPTY_VARIANT }])
  const [imageUrl, setImageUrl] = useState(product?.images[0]?.url ?? ""); const [imageAlt, setImageAlt] = useState(product?.images[0]?.altText ?? "")
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false)
  async function createCategory() { if (!categoryName.trim()) return; setPending(true); const response = await fetch("/api/catalog/categories", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: categoryName }) }); const payload = await response.json(); setPending(false); if (!response.ok) return setMessage(payload.message ?? "Não foi possível criar a categoria"); setCategories((current) => [...current, payload.category]); setCategoryId(payload.category.id); setCategoryName("") }
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setMessage(""); const body = { name, slug: slug || undefined, description, categoryId: categoryId || null, type, status, variants, images: imageUrl.trim() ? [{ url: imageUrl, altText: imageAlt }] : [], ...(product ? { expectedVersion: product.version } : {}) }; const response = await fetch(product ? `/api/catalog/products/${product.id}` : "/api/catalog/products", { method: product ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setPending(false); if (!response.ok) return setMessage(payload.message ?? (response.status === 409 ? "O cadastro mudou ou já existe" : "Não foi possível salvar")); window.location.href = `/workspace/products/${payload.product.id}` }
  function updateVariant(index: number, field: "name" | "sku" | "price", value: string) { setVariants((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item)) }
  return <main className="catalog-editor"><header><span className="eyebrow">CATÁLOGO REAL</span><h1>{product ? "Editar produto" : "Novo produto"}</h1><p>Produto e variantes persistidos na empresa ativa.</p></header>
    <section className="category-quick"><div><label htmlFor="new-category">Nova categoria</label><input id="new-category" value={categoryName} onChange={(event) => setCategoryName(event.target.value)} /></div><button type="button" disabled={pending} onClick={createCategory}>Criar categoria</button></section>
    <form onSubmit={submit}><label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Endereço<input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="gerado pelo nome" /></label><label className="wide">Descrição<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Imagem principal<input value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="/demo/produto.webp" /></label><label>Descrição da imagem<input required={Boolean(imageUrl)} value={imageAlt} onChange={(event) => setImageAlt(event.target.value)} /></label><label>Categoria<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Sem categoria</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Tipo<select value={type} onChange={(event) => { const next = event.target.value as typeof type; setType(next); setVariants(next === "SIMPLE" ? [{ ...(variants[0] ?? EMPTY_VARIANT), name: "Padrão" }] : variants) }}><option value="SIMPLE">Simples</option><option value="CONFIGURABLE">Com variantes</option></select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="DRAFT">Rascunho</option><option value="ACTIVE">Ativo</option><option value="ARCHIVED">Arquivado</option></select></label>
      <fieldset className="wide"><legend>Variantes</legend>{variants.map((variant, index) => <div className="variant-row" key={index}>{type === "CONFIGURABLE" && <label>Nome da variante<input value={variant.name} onChange={(event) => updateVariant(index, "name", event.target.value)} /></label>}<label>SKU<input value={variant.sku} onChange={(event) => updateVariant(index, "sku", event.target.value)} /></label><label>Preço<input required aria-label={index === 0 ? "Preço" : `Preço ${index + 1}`} inputMode="decimal" value={variant.price} onChange={(event) => updateVariant(index, "price", event.target.value)} /></label>{type === "CONFIGURABLE" && variants.length > 1 && <button type="button" onClick={() => setVariants((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remover</button>}</div>)}{type === "CONFIGURABLE" && <button type="button" onClick={() => setVariants((current) => [...current, { name: "", sku: "", price: "" }])}>Adicionar variante</button>}</fieldset>
      <p className="form-message" role="status">{message}</p><div className="wide form-actions"><a href="/workspace/products">Cancelar</a><button type="submit" disabled={pending}>{pending ? "Salvando…" : "Salvar produto"}</button></div></form>
  </main>
}
