"use client"
import Image from "next/image"
import { useState, type FormEvent } from "react"
import type { RecipeViewModel } from "./presenters/recipe.presenter"

type IngredientOption = { readonly id: string; readonly name: string; readonly unitLabel: string }
export function RecipeWorkspace({ recipe, ingredients, canManage }: { readonly recipe: RecipeViewModel; readonly ingredients: readonly IngredientOption[]; readonly canManage: boolean }) {
  const [yieldQuantity, setYieldQuantity] = useState(String(recipe.yieldQuantity)); const [lines, setLines] = useState(recipe.lines.map((line) => ({ ingredientId: line.ingredientId, quantity: String(line.quantityValue) }))); const [pending, setPending] = useState(false); const [message, setMessage] = useState("")
  function updateLine(index: number, field: "ingredientId" | "quantity", value: string) { setLines((current) => current.map((line, itemIndex) => itemIndex === index ? { ...line, [field]: value } : line)) }
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setMessage(""); const response = await fetch(`/api/recipes/${recipe.productId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ variantId: recipe.variantId, expectedVersion: recipe.version, yieldQuantity: Number(yieldQuantity), lines: lines.map((line) => ({ ingredientId: line.ingredientId, quantity: Number(line.quantity) })) }) }); const payload = await response.json(); setPending(false); if (!response.ok) return setMessage(response.status === 409 ? "A receita mudou. Recarregue para continuar." : payload.message ?? "Não foi possível salvar a receita"); window.location.reload() }
  return <main className="culinary-page" data-experience="culinary-v1"><section className="culinary-hero">{recipe.image ? <Image priority src={recipe.image.url} alt={recipe.image.altText} width={1200} height={900} /> : <div className="culinary-image-empty">Imagem não cadastrada</div>}<div><span className="eyebrow">SEUMEI CULINÁRIA</span><h1>{recipe.productName}</h1><p>{recipe.description}</p><dl><div><dt>Preço</dt><dd>{recipe.price}</dd></div><div><dt>Disponibilidade</dt><dd>{recipe.availability}</dd></div><div><dt>Status</dt><dd>{recipe.status}</dd></div></dl></div></section>
    <section className="recipe-card"><header><div><span className="section-index">RECEITA</span><h2>Composição por rendimento</h2></div><p>O estoque disponível limita automaticamente quantas unidades podem ser produzidas.</p></header>
      <form onSubmit={submit}><label className="recipe-yield">Rendimento<input disabled={!canManage} min="1" step="1" type="number" value={yieldQuantity} onChange={(event) => setYieldQuantity(event.target.value)} /></label><div className="recipe-lines">{lines.map((line, index) => <div key={index}><label>Ingrediente<select disabled={!canManage} required value={line.ingredientId} onChange={(event) => updateLine(index, "ingredientId", event.target.value)}><option value="">Selecione</option>{ingredients.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.unitLabel}</option>)}</select></label><label>Quantidade<input disabled={!canManage} min="1" step="1" type="number" value={line.quantity} onChange={(event) => updateLine(index, "quantity", event.target.value)} /></label>{canManage && <button type="button" onClick={() => setLines((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remover</button>}</div>)}</div>{canManage && <div className="recipe-actions"><button type="button" onClick={() => setLines((current) => [...current, { ingredientId: "", quantity: "1" }])}>Adicionar ingrediente</button><button disabled={pending || lines.length === 0}>{pending ? "Salvando…" : "Salvar receita"}</button></div>}<p role="status">{message}</p></form>
    </section></main>
}
