"use client"
import { useState, type FormEvent } from "react"

type Movement = { readonly id: string; readonly type: string; readonly quantity: string; readonly balanceAfter: string; readonly reason: string; readonly createdAt: string }
export function StockMovementPanel({ ingredient, movements, canManage }: { readonly ingredient: { readonly id: string; readonly name: string; readonly balance: string; readonly threshold: string; readonly version: number }; readonly movements: readonly Movement[]; readonly canManage: boolean }) {
  const [type, setType] = useState<"ENTRY" | "EXIT" | "RECONCILIATION">("ENTRY"); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState("")
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setMessage(""); const response = await fetch(`/api/stock/${ingredient.id}/movements`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: ingredient.version, idempotencyKey: crypto.randomUUID(), type, quantity: Number(quantity), reason }) }); const payload = await response.json(); setPending(false); if (!response.ok) return setMessage(response.status === 409 ? "Saldo alterado ou insuficiente. Recarregue antes de tentar novamente." : payload.message ?? "Não foi possível registrar o movimento"); window.location.reload() }
  return <main className="restaurant-page stock-detail" data-experience="operations-v1"><header><div><span className="eyebrow">ESTOQUE / MOVIMENTOS</span><h1>{ingredient.name}</h1><p>Saldo {ingredient.balance} · alerta {ingredient.threshold}</p></div></header>{canManage && <form className="stock-movement-form" onSubmit={submit}><label>Operação<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="ENTRY">Entrada</option><option value="EXIT">Saída</option><option value="RECONCILIATION">Reconciliação para saldo</option></select></label><label>Quantidade<input required min="0" step="1" type="number" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label>Motivo<input required value={reason} onChange={(event) => setReason(event.target.value)} /></label><button disabled={pending}>{pending ? "Registrando…" : "Registrar movimento"}</button><p role="status">{message}</p></form>}<section className="movement-list"><h2>Histórico imutável</h2>{movements.length === 0 ? <p>Nenhum movimento registrado.</p> : movements.map((item) => <article key={item.id}><strong>{item.type}</strong><span>{item.quantity}</span><span>Saldo {item.balanceAfter}</span><p>{item.reason}</p><time>{item.createdAt}</time></article>)}</section></main>
}
