"use client"

import Link from "next/link"
import { useMemo, useState, type CSSProperties, type FormEvent } from "react"
import type { toStoreDesignViewModel } from "./presenters/store-design.presenter"

type View = ReturnType<typeof toStoreDesignViewModel>
type Preset = View["presets"][number]

function previewStyle(preset: Preset): CSSProperties {
  return { "--preview-bg": preset.tokens.background, "--preview-fg": preset.tokens.foreground, "--preview-surface": preset.tokens.surface, "--preview-muted": preset.tokens.muted, "--preview-accent": preset.tokens.accent, "--preview-accent-fg": preset.tokens.accentForeground, "--preview-border": preset.tokens.border, "--preview-radius": preset.tokens.radius } as CSSProperties
}

export function StoreDesignStudio({ view }: { readonly view: View }) {
  const [presetId, setPresetId] = useState(view.preset); const [headline, setHeadline] = useState(view.headline); const [announcement, setAnnouncement] = useState(view.announcement); const [description, setDescription] = useState(view.description); const [heroImageUrl, setHeroImageUrl] = useState(view.heroImageUrl)
  const [version, setVersion] = useState(view.draftVersion); const [dirty, setDirty] = useState(false); const [pending, setPending] = useState(false); const [message, setMessage] = useState("")
  const preset = useMemo(() => view.presets.find(({ id }) => id === presetId) ?? view.presets[0]!, [presetId, view.presets])
  function change(action: () => void) { action(); setDirty(true); setMessage("") }
  async function save(event?: FormEvent) { event?.preventDefault(); setPending(true); setMessage(""); const response = await fetch("/api/store/design", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: version, preset: presetId, headline, announcement, description, heroImageUrl: heroImageUrl || null }) }); const payload = await response.json(); setPending(false); if (!response.ok) { setMessage(response.status === 409 ? "O rascunho mudou em outra sessão. Atualize para continuar." : payload.message ?? "Não foi possível salvar o rascunho."); return false } setVersion(payload.draft.draftVersion); setDirty(false); setMessage("Rascunho salvo."); return true }
  async function publication(action: "publish" | "unpublish") { if (dirty) { setMessage("Salve o rascunho antes de publicar."); return } setPending(true); setMessage(""); const response = await fetch(`/api/store/design/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: version }) }); const payload = await response.json(); setPending(false); if (!response.ok) { setMessage(response.status === 409 ? "A publicação mudou. Atualize a página." : payload.message ?? "Não foi possível atualizar a publicação."); return } window.location.reload() }
  return <main className="store-studio-page"><header><div><span className="eyebrow">ESTÚDIO DA MARCA</span><h1>Identidade da loja</h1><p>Escolha uma direção, revise no contexto e publique somente quando estiver pronto.</p></div><div className="store-studio-status"><span>{view.statusLabel}</span><Link href="/workspace/store/preview">Abrir preview privado</Link>{view.isPublished && <a href={view.publicUrl} target="_blank" rel="noreferrer">Ver loja publicada</a>}</div></header>
    <section className="store-studio-workbench"><form onSubmit={save} className="store-studio-controls"><fieldset><legend>Direção visual</legend><div className="store-preset-list">{view.presets.map((item) => <button type="button" aria-pressed={presetId === item.id} onClick={() => change(() => setPresetId(item.id))} key={item.id} style={previewStyle(item)}><i aria-hidden="true" /><span><strong>{item.name}</strong><small>{item.description}</small></span></button>)}</div></fieldset><label>Título principal<input value={headline} minLength={3} maxLength={80} required onChange={(event) => change(() => setHeadline(event.target.value))} /></label><label>Aviso curto<input value={announcement} maxLength={60} onChange={(event) => change(() => setAnnouncement(event.target.value))} placeholder="Ex.: Retirada em 20 minutos" /></label><label>Descrição<textarea rows={4} minLength={10} maxLength={280} required value={description} onChange={(event) => change(() => setDescription(event.target.value))} /></label><label>Imagem hero<input value={heroImageUrl} onChange={(event) => change(() => setHeroImageUrl(event.target.value))} placeholder="/demo/galaxia-smash.webp" /></label><p className="form-message" role="status">{message}</p><button className="store-save" disabled={pending}>{pending ? "Salvando…" : "Salvar rascunho"}</button></form>
      <div className="store-studio-preview" style={previewStyle(preset)} data-family={preset.displayFamily}><div className="preview-chrome"><span>RASCUNHO AO VIVO</span><strong>{view.storeSlug}</strong></div><div className="preview-hero">{announcement && <small>{announcement}</small>}<h2>{headline || view.displayName}</h2><p>{description}</p><button>Explorar cardápio</button></div><article><span>DESTAQUE DO CATÁLOGO</span><h3>Seu produto aparece aqui</h3><p>Imagens, preços e disponibilidade reais entram no preview privado.</p></article></div>
    </section><footer className="store-publication-bar"><div><strong>{dirty ? "Alterações ainda não salvas" : "Rascunho sincronizado"}</strong><span>Publicar cria uma versão imutável e atualiza a loja pública.</span></div><div>{view.isPublished && <button className="secondary" disabled={pending || dirty} onClick={() => publication("unpublish")}>Despublicar</button>}<button disabled={pending || dirty} onClick={() => publication("publish")}>Publicar versão</button></div></footer>
  </main>
}
