import { resolveActiveCompanyContext } from "../application/active-company"
import { advanceOrder, checkoutPublicStore, readCustomer, readCustomers, readOrder, readOrders } from "../application/commerce-service"
import type { CommerceOrderStatus } from "../domain/commerce"
import type { CompanyRepository } from "../domain/repositories/company-repository"
import type { CompleteCoreAccessRepository } from "../domain/repositories/core-access-repository"
import type { CommerceRepository } from "../domain/repositories/commerce-repository"
import { CheckoutConflictError, CheckoutStockUnavailableError, StoreUnavailableError } from "../infrastructure/commerce.repository"
import type { SessionActor } from "../types/session-actor"
import type { HttpResult } from "./company-handlers"

export interface CommerceHttpServices { core: CompleteCoreAccessRepository; companies: CompanyRepository; commerce: CommerceRepository }
const record = (value: unknown): value is Record<string, any> => Boolean(value) && typeof value === "object" && !Array.isArray(value)
export async function checkoutHandler(storeSlug: string, body: unknown, commerce: CommerceRepository): Promise<HttpResult> {
  if (!record(body) || Object.hasOwn(body, "tenantId") || Object.hasOwn(body, "priceCents") || typeof body.variantId !== "string" || !Number.isInteger(body.quantity) || typeof body.name !== "string" || typeof body.email !== "string" || typeof body.idempotencyKey !== "string") return { status: 400, body: { error: "invalid_request" } }
  try { return { status: 201, body: { order: await checkoutPublicStore(storeSlug, body as any, commerce) } } } catch (error) { if (error instanceof StoreUnavailableError) return { status: 404, body: { error: "store_unavailable" } }; if (error instanceof CheckoutStockUnavailableError) return { status: 409, body: { error: "insufficient_stock" } }; if (error instanceof CheckoutConflictError) return { status: 409, body: { error: "checkout_conflict" } }; return { status: 400, body: { error: "invalid_request" } } }
}
async function context(actor: SessionActor, companyId: string, services: CommerceHttpServices) { return resolveActiveCompanyContext(actor, companyId, services.core, services.companies) }
export async function listOrdersHandler(actor: SessionActor, companyId: string, services: CommerceHttpServices): Promise<HttpResult> { try { return { status: 200, body: { orders: await readOrders(await context(actor, companyId, services), services.commerce) } } } catch { return { status: 403, body: { error: "commerce_forbidden" } } } }
export async function readOrderHandler(actor: SessionActor, companyId: string, orderId: string, services: CommerceHttpServices): Promise<HttpResult> { try { const item = await readOrder(await context(actor, companyId, services), orderId, services.commerce); return item ? { status: 200, body: { order: item } } : { status: 404, body: { error: "order_not_found" } } } catch { return { status: 403, body: { error: "commerce_forbidden" } } } }
export async function transitionOrderHandler(actor: SessionActor, companyId: string, orderId: string, body: unknown, services: CommerceHttpServices): Promise<HttpResult> { if (!record(body) || Object.hasOwn(body, "tenantId") || !Number.isInteger(body.expectedVersion) || !["CONFIRMED", "PREPARING", "READY", "COMPLETED", "CANCELLED"].includes(body.status)) return { status: 400, body: { error: "invalid_request" } }; try { const item = await advanceOrder(await context(actor, companyId, services), orderId, body.expectedVersion, body.status as CommerceOrderStatus, services.commerce); return item ? { status: 200, body: { order: item } } : { status: 404, body: { error: "order_not_found" } } } catch (error) { return { status: error instanceof CheckoutConflictError ? 409 : 403, body: { error: error instanceof CheckoutConflictError ? "order_conflict" : "commerce_forbidden" } } } }
export async function listCustomersHandler(actor: SessionActor, companyId: string, services: CommerceHttpServices): Promise<HttpResult> { try { return { status: 200, body: { customers: await readCustomers(await context(actor, companyId, services), services.commerce) } } } catch { return { status: 403, body: { error: "commerce_forbidden" } } } }
export async function readCustomerHandler(actor: SessionActor, companyId: string, customerId: string, services: CommerceHttpServices): Promise<HttpResult> { try { const item = await readCustomer(await context(actor, companyId, services), customerId, services.commerce); return item ? { status: 200, body: { customer: item } } : { status: 404, body: { error: "customer_not_found" } } } catch { return { status: 403, body: { error: "commerce_forbidden" } } } }
