export interface ComponentMetadata {
  readonly name: string
  readonly description: string
  readonly category: "layout" | "typography" | "action" | "form" | "feedback" | "context"
  readonly status: "experimental" | "beta" | "stable" | "deprecated"
  readonly source: string
  readonly tags: readonly string[]
  readonly tokens: readonly string[]
  readonly accessibility: readonly string[]
  readonly related: readonly string[]
  readonly deprecated?: { readonly replacement: string; readonly since: string }
}

export const componentMetadata = [
  {
    name: "Stack",
    description: "Arranges content vertically with a consistent semantic gap.",
    category: "layout",
    status: "stable",
    source: "layout.tsx",
    tags: ["flow", "spacing"],
    tokens: ["--matriz-space-*"],
    accessibility: ["Preserves native child order."],
    related: ["Inline", "Container"],
  },
  {
    name: "Inline",
    description: "Arranges related content horizontally and optionally wraps it.",
    category: "layout",
    status: "stable",
    source: "layout.tsx",
    tags: ["flow", "spacing", "wrap"],
    tokens: ["--matriz-space-*"],
    accessibility: ["Preserves native child order."],
    related: ["Stack"],
  },
  {
    name: "Container",
    description: "Constrains page content and provides responsive inline space.",
    category: "layout",
    status: "stable",
    source: "layout.tsx",
    tags: ["page", "width"],
    tokens: ["--matriz-space-4", "--matriz-space-6", "--matriz-space-8"],
    accessibility: ["Does not alter document semantics."],
    related: ["Stack", "Surface"],
  },
  {
    name: "Surface",
    description: "Groups content on a semantic background and border.",
    category: "layout",
    status: "stable",
    source: "layout.tsx",
    tags: ["panel", "card"],
    tokens: ["--matriz-color-surface", "--matriz-color-border", "--matriz-elevation-*"],
    accessibility: ["Accepts native region attributes when a landmark is needed."],
    related: ["Container"],
  },
  {
    name: "Heading",
    description: "Renders a native heading at an explicit hierarchy level.",
    category: "typography",
    status: "stable",
    source: "typography.tsx",
    tags: ["heading", "hierarchy"],
    tokens: ["--matriz-color-text", "--matriz-font-sans"],
    accessibility: ["Uses native h1 through h4 elements."],
    related: ["Text"],
  },
  {
    name: "Text",
    description: "Renders readable body text with semantic tone and size options.",
    category: "typography",
    status: "stable",
    source: "typography.tsx",
    tags: ["body", "copy"],
    tokens: ["--matriz-color-text", "--matriz-color-text-muted"],
    accessibility: ["Uses a native paragraph element."],
    related: ["Heading"],
  },
  {
    name: "Button",
    description: "Triggers an action through a native button element.",
    category: "action",
    status: "stable",
    source: "actions.tsx",
    tags: ["action", "control"],
    tokens: ["--matriz-color-action", "--matriz-color-focus", "--matriz-radius-md"],
    accessibility: ["Defaults to type button.", "Preserves native disabled behavior."],
    related: ["InfoHint"],
  },
  {
    name: "Label",
    description: "Names a native form control.",
    category: "form",
    status: "stable",
    source: "forms.tsx",
    tags: ["form", "name"],
    tokens: ["--matriz-color-text"],
    accessibility: ["Uses the native label element and htmlFor contract."],
    related: ["Input", "FormField"],
  },
  {
    name: "Input",
    description: "Collects a single native text value with forwarded focus access.",
    category: "form",
    status: "stable",
    source: "forms.tsx",
    tags: ["form", "text-entry"],
    tokens: ["--matriz-color-surface", "--matriz-color-border", "--matriz-color-focus"],
    accessibility: ["Forwards native input attributes and its ref.", "Consumes FormField descriptions."],
    related: ["Label", "FormField"],
  },
  {
    name: "FormField",
    description: "Connects one field label, helper text, and validation feedback.",
    category: "form",
    status: "stable",
    source: "forms.tsx",
    tags: ["form", "validation", "description"],
    tokens: ["--matriz-color-text-muted", "--matriz-color-danger"],
    accessibility: ["Connects descriptions with aria-describedby.", "Announces validation feedback politely."],
    related: ["Label", "Input"],
  },
  {
    name: "Badge",
    description: "Displays a compact semantic state label.",
    category: "feedback",
    status: "stable",
    source: "feedback.tsx",
    tags: ["status", "label"],
    tokens: ["--matriz-color-success", "--matriz-color-warning", "--matriz-color-danger"],
    accessibility: ["Communicates state through text in addition to color."],
    related: ["Alert"],
  },
  {
    name: "Alert",
    description: "Announces informational, successful, warning, or dangerous feedback.",
    category: "feedback",
    status: "stable",
    source: "feedback.tsx",
    tags: ["status", "message", "live-region"],
    tokens: ["--matriz-color-info", "--matriz-color-success", "--matriz-color-warning", "--matriz-color-danger"],
    accessibility: ["Uses status for polite feedback and alert for urgent feedback."],
    related: ["Badge", "EmptyState"],
  },
  {
    name: "EmptyState",
    description: "Explains an empty region and optionally presents a next action.",
    category: "feedback",
    status: "stable",
    source: "feedback.tsx",
    tags: ["empty", "placeholder"],
    tokens: ["--matriz-color-canvas", "--matriz-color-border", "--matriz-color-text-muted"],
    accessibility: ["Uses a native heading for the empty-state title."],
    related: ["Alert", "Button"],
  },
  {
    name: "InfoHint",
    description: "Reveals concise supporting context from pointer or keyboard input.",
    category: "context",
    status: "beta",
    source: "info-hint.tsx",
    tags: ["tooltip", "context", "keyboard"],
    tokens: ["--matriz-color-surface", "--matriz-color-focus", "--matriz-elevation-md"],
    accessibility: ["Opens on focus.", "Closes on Escape and restores trigger focus."],
    related: ["Button", "Text"],
  },
] as const satisfies readonly ComponentMetadata[]
