import { createCipheriv, createDecipheriv, createHash, randomBytes, verify as verifySignature, type JsonWebKey as NodeJsonWebKey } from "node:crypto"
import type { AuthSession } from "../v1/types"
import type { MockAuthBroker } from "../v1/mock/mock-auth-broker"
import { createHttpMockAuthBroker } from "../v1/mock/mock-auth-broker"
import type { SharedAuthSession } from "../v1/mock/mock-auth"

export type OidcBffConfig = Readonly<{ issuer: string; clientId: string; clientSecret: string; appId: string; callbackUrl: string; sessionSecret: string }>
type Correlation = { state: string; nonce: string; verifier: string; returnTo: string }
type AccessProjection = { context: { userId: string; tenantId: string; appId: string; membershipId: string; tenantRoles: string[]; appRoles: string[]; capabilities: string[]; sessionId: string }; user: { id: string; name?: string; email?: string }; eligibleTenants: Array<{ tenantId: string; tenantName: string; membershipId: string; tenantRoles: string[]; appRoles: string[]; capabilities: string[] }>; switchCsrfToken: string; tokens?: { accessToken: string } }
export type OidcAuthorizationContext = AccessProjection["context"] & { traceId: string }
export type OidcStoredSession = { session: AuthSession; context: AccessProjection["context"]; refreshToken?: string; accessToken: string; accessExpiresAt: number; idToken: string; switchCsrfToken: string; vaultRevision?: number; refreshLeaseUntil?: number }
type StoredSession = OidcStoredSession
export interface OidcSessionVault {
  create(value: OidcStoredSession): Promise<string>
  read(handle: string): Promise<OidcStoredSession | null>
  rotate(handle: string, value: OidcStoredSession): Promise<string>
  update(handle: string, value: OidcStoredSession): Promise<boolean>
  delete(handle: string): Promise<void>
}

export const OIDC_CORRELATION_COOKIE = "__Host-matriz_oidc_flow"
export const OIDC_SESSION_COOKIE = "__Host-matriz_session"
export function oidcSessionCookieOptions() { return { httpOnly: true, secure: true, sameSite: "lax" as const, path: "/" } }

function requireConfig(config: OidcBffConfig) {
  const issuer = new URL(config.issuer); const callback = new URL(config.callbackUrl)
  if (process.env.NODE_ENV === "production" && (issuer.protocol !== "https:" || callback.protocol !== "https:")) throw new Error("OIDC URLs require HTTPS")
  if (!config.clientId || config.clientSecret.length < 32 || config.sessionSecret.length < 32) throw new Error("Invalid confidential OIDC client configuration")
  return { issuer: issuer.toString().replace(/\/$/, ""), callback: callback.toString() }
}
function digest(value: string) { return createHash("sha256").update(value).digest("base64url") }
function key(secret: string) { return createHash("sha256").update(secret).digest() }
function seal(value: unknown, secret: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(secret), iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(value)), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString("base64url") }
function open<T>(value: string, secret: string): T { const raw = Buffer.from(value, "base64url"); const decipher = createDecipheriv("aes-256-gcm", key(secret), raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return JSON.parse(Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString("utf8")) as T }
function cookie(request: Request, name: string) { return request.headers.get("cookie")?.split(";").map(v => v.trim()).find(v => v.startsWith(`${name}=`))?.slice(name.length + 1) }
function setCookie(name: string, value: string, maxAge: number) { return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}` }
const serverSessions = new Map<string, StoredSession>()
function storeSession(value: StoredSession, previous?: string) { if (previous) serverSessions.delete(digest(previous)); if (serverSessions.size >= 10_000) serverSessions.delete(serverSessions.keys().next().value!); const id = randomBytes(32).toString("base64url"); serverSessions.set(digest(id), value); return id }
function loadSession(id?: string) { return id ? serverSessions.get(digest(id)) : undefined }
function deleteSession(id?: string) { if (id) serverSessions.delete(digest(id)) }
function vaultFor(config: OidcBffConfig): OidcSessionVault { if (process.env.NODE_ENV === "production") return createIdentitySessionVault(config); return { create: async value => storeSession({ ...value, vaultRevision: 0 }), read: async handle => loadSession(handle) ?? null, rotate: async (handle, value) => storeSession({ ...value, vaultRevision: 0 }, handle), update: async (handle, value) => { const current = loadSession(handle); if (!current || current.vaultRevision !== value.vaultRevision) return false; serverSessions.set(digest(handle), { ...value, vaultRevision: (value.vaultRevision ?? 0) + 1 }); return true }, delete: async handle => deleteSession(handle) } }
export function establishOidcServerSession(value: StoredSession): string { return storeSession(value) }
export function resolveOidcServerSession(request: Request): { session: AuthSession; context: OidcAuthorizationContext; opaqueId: string } | null { const id = cookie(request, OIDC_SESSION_COOKIE); const stored = loadSession(id); if (!id || !stored || Date.parse(stored.session.expiresAt) <= Date.now()) return null; return { session: stored.session, context: Object.freeze({ ...stored.context, traceId: request.headers.get("traceparent") ?? randomBytes(16).toString("hex") }), opaqueId: id } }
export async function resolveOidcServerSessionDurable(request: Request, config: OidcBffConfig): Promise<{ session: AuthSession; context: OidcAuthorizationContext; opaqueId: string; accessToken: string } | null> { const id = cookie(request, OIDC_SESSION_COOKIE); if (!id) return null; const vault = vaultFor(config); let stored = await vault.read(id); if (!stored || Date.parse(stored.session.expiresAt) <= Date.now()) return null; const issuer = requireConfig(config).issuer; if (stored.accessExpiresAt <= Date.now() + 30_000) { stored = await refreshWithLease(id, stored, vault, config, issuer); if (!stored) return null }; const active = await fetch(`${issuer}/api/access/exchange`, { method: "POST", headers: { authorization: `Bearer ${stored.accessToken}`, "content-type": "application/json" }, body: JSON.stringify({ tenantId: stored.session.activeTenantId }), cache: "no-store" }); if (!active.ok) { await vault.delete(id); return null }; const projection = await active.json() as AccessProjection; return { session: stored.session, context: Object.freeze({ ...projection.context, traceId: request.headers.get("traceparent") ?? randomBytes(16).toString("hex") }), opaqueId: id, accessToken: stored.accessToken } }

async function refreshWithLease(id: string, stored: OidcStoredSession, vault: OidcSessionVault, config: OidcBffConfig, issuer: string): Promise<OidcStoredSession | null> {
  if (!stored.refreshToken) { await vault.delete(id); return null }
  const claimed = { ...stored, refreshLeaseUntil: Date.now() + 10_000 }
  if (!await vault.update(id, claimed)) {
    for (let attempt = 0; attempt < 20; attempt++) { await new Promise(resolve => setTimeout(resolve, 10)); const winner = await vault.read(id); if (!winner) return null; if (winner.accessExpiresAt > Date.now() + 30_000) return winner }
    return null
  }
  claimed.vaultRevision = (claimed.vaultRevision ?? 0) + 1
  const discovery = await metadata(issuer)
  const refreshed = await fetch(discovery.token_endpoint, { method: "POST", headers: { authorization: `Basic ${Buffer.from(`${config.clientId}:${config.clientSecret}`).toString("base64")}`, "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: claimed.refreshToken! }) })
  if (!refreshed.ok) { await vault.delete(id); return null }
  const token = await refreshed.json() as { access_token: string; refresh_token?: string; expires_in?: number }
  const next = { ...claimed, accessToken: token.access_token, accessExpiresAt: Date.now() + (token.expires_in ?? 300) * 1000, refreshLeaseUntil: undefined, ...(token.refresh_token ? { refreshToken: token.refresh_token } : {}) }
  if (!await vault.update(id, next)) return await vault.read(id)
  return { ...next, vaultRevision: (next.vaultRevision ?? 0) + 1 }
}
export function createIdentitySessionVault(config: OidcBffConfig): OidcSessionVault { const root = requireConfig(config).issuer; const auth = `Basic ${Buffer.from(`${config.clientId}:${config.clientSecret}`).toString("base64")}`; const call = async <T>(path: string, body: unknown): Promise<T> => { const response = await fetch(`${root}/api/app-sessions/${path}`, { method: "POST", headers: { authorization: auth, "content-type": "application/json" }, body: JSON.stringify(body), cache: "no-store" }); if (!response.ok) throw Object.assign(new Error("Identity session vault rejected the operation"), { status: response.status }); return await response.json() as T }; return { create: async value => (await call<{ handle: string }>("create", { appId: config.appId, value })).handle, read: async handle => (await call<{ value: OidcStoredSession | null }>("read", { appId: config.appId, handle })).value, rotate: async (handle, value) => (await call<{ handle: string }>("rotate", { appId: config.appId, handle, value })).handle, update: async (handle, value) => { try { await call("update", { appId: config.appId, handle, value, expectedRevision: value.vaultRevision ?? 0 }); return true } catch (error) { if ((error as { status?: number }).status === 409) return false; throw error } }, delete: async handle => { await call("delete", { appId: config.appId, handle }) } } }
function safeReturnTo(value: string | null) { return value?.startsWith("/") && !value.startsWith("//") ? value : "/" }

export async function createOidcAuthorizationRequest(config: OidcBffConfig, returnTo = "/") {
  const { issuer, callback } = requireConfig(config); const verifier = randomBytes(32).toString("base64url")
  const flow: Correlation = { state: randomBytes(24).toString("base64url"), nonce: randomBytes(24).toString("base64url"), verifier, returnTo: safeReturnTo(returnTo) }
  const url = new URL(`${issuer}/auth`); url.search = new URLSearchParams({ client_id: config.clientId, redirect_uri: callback, response_type: "code", scope: "openid profile email offline_access matriz_access", code_challenge: digest(verifier), code_challenge_method: "S256", state: flow.state, nonce: flow.nonce }).toString()
  return { authorizationUrl: url.toString(), correlationCookie: seal(flow, config.sessionSecret) }
}

async function metadata(issuer: string) { const response = await fetch(`${issuer}/.well-known/openid-configuration`, { cache: "no-store" }); if (!response.ok) throw new Error("OIDC discovery failed"); return await response.json() as { issuer: string; token_endpoint: string; jwks_uri: string; revocation_endpoint?: string } }
function decodePart<T>(part: string): T { return JSON.parse(Buffer.from(part, "base64url").toString("utf8")) as T }
async function validateIdToken(token: string, expected: { issuer: string; audience: string; nonce: string }, jwksUri: string) {
  const [head, body, signature] = token.split("."); if (!head || !body || !signature) throw new Error("Invalid ID token")
  const header = decodePart<{ alg: string; kid: string }>(head); const claims = decodePart<{ iss: string; aud: string | string[]; exp: number; nonce?: string; sub: string; name?: string; email?: string }>(body)
  if (header.alg !== "RS256" || claims.iss !== expected.issuer || !(Array.isArray(claims.aud) ? claims.aud : [claims.aud]).includes(expected.audience) || claims.nonce !== expected.nonce || claims.exp * 1000 <= Date.now()) throw new Error("ID token claims rejected")
  const response = await fetch(jwksUri, { cache: "no-store" }); const keys = (await response.json() as { keys: JsonWebKey[] }).keys; const jwk = keys.find(item => (item as JsonWebKey & { kid?: string }).kid === header.kid); if (!jwk) throw new Error("Unknown signing key")
  if (!verifySignature("RSA-SHA256", Buffer.from(`${head}.${body}`), { key: jwk as NodeJsonWebKey, format: "jwk" }, Buffer.from(signature, "base64url"))) throw new Error("Invalid ID token signature")
  return claims
}

export function createOidcLoginRoute(config: OidcBffConfig) { return async (request: Request) => { const result = await createOidcAuthorizationRequest(config, new URL(request.url).searchParams.get("returnTo") ?? "/"); return new Response(null, { status: 302, headers: { location: result.authorizationUrl, "set-cookie": setCookie(OIDC_CORRELATION_COOKIE, result.correlationCookie, 600), "cache-control": "no-store" } }) } }
export function createOidcCallbackRoute(config: OidcBffConfig) { return async (request: Request) => {
  const { issuer, callback } = requireConfig(config); const url = new URL(request.url); const flowCookie = cookie(request, OIDC_CORRELATION_COOKIE); if (!flowCookie) return new Response("Missing correlation", { status: 400 })
  let flow: Correlation; try { flow = open(flowCookie, config.sessionSecret) } catch { return new Response("Invalid correlation", { status: 400 }) }
  if (!url.searchParams.get("code") || url.searchParams.get("state") !== flow.state) return new Response("Invalid callback", { status: 400 })
  const discovery = await metadata(issuer); if (discovery.issuer !== issuer) return new Response("Issuer mismatch", { status: 502 })
  const tokens = await fetch(discovery.token_endpoint, { method: "POST", headers: { authorization: `Basic ${Buffer.from(`${config.clientId}:${config.clientSecret}`).toString("base64")}`, "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", code: url.searchParams.get("code")!, redirect_uri: callback, code_verifier: flow.verifier }) })
  if (!tokens.ok) return new Response("Token exchange rejected", { status: 401 }); const token = await tokens.json() as { access_token: string; id_token: string; refresh_token?: string; expires_in?: number }
  const claims = await validateIdToken(token.id_token, { issuer, audience: config.clientId, nonce: flow.nonce }, discovery.jwks_uri)
  const access = await fetch(`${issuer}/api/access/exchange`, { method: "POST", headers: { authorization: `Bearer ${token.access_token}`, "content-type": "application/json", origin: new URL(callback).origin }, body: "{}" }); if (!access.ok) return new Response("App access denied", { status: 403 })
  const projection = await access.json() as AccessProjection; if (projection.context.appId !== config.appId) return new Response("App binding rejected", { status: 403 })
  const now = new Date(); const session: AuthSession = { identity: { user: { id: projection.context.userId as never, name: claims.name ?? projection.user.name ?? "Matriz user", email: claims.email ?? projection.user.email ?? "" }, tenants: projection.eligibleTenants.map(item => ({ tenantId: item.tenantId as never, tenantName: item.tenantName, roles: item.tenantRoles, enabledApps: [config.appId as never] })) }, activeTenantId: projection.context.tenantId as never, strategyId: "oidc", issuedAt: now.toISOString(), expiresAt: new Date(now.getTime() + 8 * 60 * 60_000).toISOString() }
  const stored: StoredSession = { session, context: projection.context, accessToken: token.access_token, accessExpiresAt: Date.now() + (token.expires_in ?? 300) * 1000, idToken: token.id_token, switchCsrfToken: projection.switchCsrfToken, ...(token.refresh_token ? { refreshToken: token.refresh_token } : {}) }
  const vault = vaultFor(config); const previous = cookie(request, OIDC_SESSION_COOKIE); if (previous) await vault.delete(previous); const headers = new Headers({ location: new URL(flow.returnTo, callback).toString(), "cache-control": "no-store" }); headers.append("set-cookie", setCookie(OIDC_SESSION_COOKIE, await vault.create(stored), 8 * 60 * 60)); headers.append("set-cookie", setCookie(OIDC_CORRELATION_COOKIE, "", 0)); return new Response(null, { status: 302, headers })
} }
export function createOidcSessionRoute(config: OidcBffConfig) { return async (request: Request) => { const id = cookie(request, OIDC_SESSION_COOKIE); const vault = vaultFor(config); const stored = id ? await vault.read(id) : null; if (!id || !stored || Date.parse(stored.session.expiresAt) <= Date.now()) { if (id) await vault.delete(id); return new Response(null, { status: 401 }) }; const issuer = requireConfig(config).issuer; if (stored.accessExpiresAt <= Date.now() + 30_000) { if (!stored.refreshToken) { await vault.delete(id); return new Response(null, { status: 401 }) }; const discovery = await metadata(issuer); const refreshed = await fetch(discovery.token_endpoint, { method: "POST", headers: { authorization: `Basic ${Buffer.from(`${config.clientId}:${config.clientSecret}`).toString("base64")}`, "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: stored.refreshToken }) }); if (!refreshed.ok) { await vault.delete(id); return new Response(null, { status: 401 }) }; const token = await refreshed.json() as { access_token: string; refresh_token?: string; expires_in?: number }; stored.accessToken = token.access_token; stored.accessExpiresAt = Date.now() + (token.expires_in ?? 300) * 1000; if (token.refresh_token) stored.refreshToken = token.refresh_token }; const active = await fetch(`${issuer}/api/access/exchange`, { method: "POST", headers: { authorization: `Bearer ${stored.accessToken}`, "content-type": "application/json" }, body: JSON.stringify({ tenantId: stored.session.activeTenantId }) }); if (!active.ok) { await vault.delete(id); return new Response(null, { status: 401 }) }; const projection = await active.json() as AccessProjection; stored.context = projection.context; stored.switchCsrfToken = projection.switchCsrfToken; const nextId = await vault.rotate(id, stored); return Response.json({ session: stored.session, recentApps: [] } satisfies SharedAuthSession, { headers: { "set-cookie": setCookie(OIDC_SESSION_COOKIE, nextId, 8 * 60 * 60), "cache-control": "no-store, private" } }) } }
export function createOidcLogoutRoute(config: OidcBffConfig) { return async (request: Request) => { const origin = request.headers.get("origin"); if (!origin || origin !== new URL(config.callbackUrl).origin || request.headers.get("x-matriz-csrf") !== "1") return new Response("Invalid origin", { status: 403 }); const id = cookie(request, OIDC_SESSION_COOKIE); const vault = vaultFor(config); try { const stored = id ? await vault.read(id) : null; if (stored?.refreshToken) { const discovery = await metadata(requireConfig(config).issuer); if (discovery.revocation_endpoint) await fetch(discovery.revocation_endpoint, { method: "POST", headers: { authorization: `Basic ${Buffer.from(`${config.clientId}:${config.clientSecret}`).toString("base64")}`, "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ token: stored.refreshToken, token_type_hint: "refresh_token" }) }) } } catch { /* remote revocation is best effort */ } finally { if (id) await vault.delete(id) }; return new Response(null, { status: 204, headers: { "set-cookie": setCookie(OIDC_SESSION_COOKIE, "", 0), "cache-control": "no-store" } }) } }
export function createOidcTenantSwitchRoute(config: OidcBffConfig) { return async (request: Request) => { const origin = request.headers.get("origin"); if (!origin || origin !== new URL(config.callbackUrl).origin) return new Response("Invalid origin", { status: 403 }); const id = cookie(request, OIDC_SESSION_COOKIE); const vault = vaultFor(config); const stored = id ? await vault.read(id) : null; if (!id || !stored) return new Response(null, { status: 401 }); const body = await request.json() as { tenantId?: string }; const issuer = requireConfig(config).issuer; const response = await fetch(`${issuer}/api/access/switch`, { method: "POST", headers: { authorization: `Bearer ${stored.accessToken}`, "content-type": "application/json", origin: new URL(issuer).origin, "x-csrf-token": stored.switchCsrfToken }, body: JSON.stringify({ tenantId: body.tenantId }) }); if (!response.ok) return new Response("Switch denied", { status: response.status }); const projection = await response.json() as AccessProjection; if (!projection.tokens?.accessToken) return new Response("Switch token missing", { status: 502 }); const next: StoredSession = { ...stored, context: projection.context, accessToken: projection.tokens.accessToken, accessExpiresAt: Date.now() + 5 * 60_000, switchCsrfToken: projection.switchCsrfToken, session: { ...stored.session, activeTenantId: projection.context.tenantId as never } }; const newId = await vault.rotate(id, next); return Response.json(next.session, { headers: { "set-cookie": setCookie(OIDC_SESSION_COOKIE, newId, 8 * 60 * 60), "cache-control": "no-store" } }) } }

export function createHttpOidcAuthBroker(root = "/api/auth/oidc"): MockAuthBroker { const redirect = (): Promise<never> => { if (typeof window === "undefined") return Promise.reject(new Error("OIDC login requires a browser")); window.location.assign(`${root}/login`); return new Promise(() => undefined) }; const request = async <T>(path: string, init?: RequestInit) => { const response = await fetch(`${root}${path}`, { ...init, credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json", ...init?.headers } }); if (response.status === 401) return null as T; if (!response.ok) throw new Error("OIDC session unavailable"); return response.status === 204 ? undefined as T : await response.json() as T }; return { startChallenge: redirect, verifyOtp: redirect, verifyMagicLink: redirect, signInWithGoogle: redirect, signInWithEmail: redirect, restoreSession: () => request("/session"), recordAppOpen: async () => undefined, signOut: () => request("/session", { method: "DELETE", headers: { "x-matriz-csrf": "1" } }), switchTenant: (tenantId) => request("/tenant", { method: "POST", body: JSON.stringify({ tenantId }) }) } }
export function createConfiguredAuthBroker(input: { developmentMockBaseUrl: string }): MockAuthBroker {
  if (process.env.NODE_ENV !== "production" && process.env.NEXT_PUBLIC_MATRIZ_AUTH_ADAPTER === "mock") return createHttpMockAuthBroker(input.developmentMockBaseUrl)
  return createHttpOidcAuthBroker()
}
