import type { DesktopGateway } from "../../application/desktop-gateway"

export const TAURI_COMMAND_CONTRACT = Object.freeze({
  snapshot: "get_snapshot",
  kill: "terminate_process",
  killMany: "terminate_processes",
  startApp: "start_app",
  stopApp: "stop_app",
  appStatuses: "get_app_statuses",
  runGate: "run_gate",
  openTarget: "open_target",
  selectWorkspace: "select_workspace",
  doctor: "run_doctor",
  workspacePulse: "get_workspace_pulse",
  readSettings: "read_settings",
  writeSettings: "write_settings",
  hide: "hide_window",
  quit: "quit_app",
  createTerminal: "create_terminal",
  writeTerminal: "write_terminal",
  resizeTerminal: "resize_terminal",
  interruptTerminal: "interrupt_terminal",
  closeTerminal: "close_terminal",
  listTerminals: "list_terminals",
  subscribeTerminal: "subscribe_terminal",
  startManagedOperation: "start_managed_operation",
  getNativeAppRuntime: "get_native_app_runtime",
  installNativeApp: "install_native_app",
  startNativeApp: "start_native_app",
} as const satisfies Readonly<Record<keyof DesktopGateway, string>>)
