SET search_path TO "hub";

-- Remove id-only foreign keys before installing tenant-bound equivalents.
ALTER TABLE "doc_documents" DROP CONSTRAINT "doc_documents_currentVersionId_fkey";
ALTER TABLE "doc_document_versions" DROP CONSTRAINT "doc_document_versions_documentId_fkey";
ALTER TABLE "doc_blocks" DROP CONSTRAINT "doc_blocks_documentId_fkey";
ALTER TABLE "doc_blocks" DROP CONSTRAINT "doc_blocks_versionId_fkey";
ALTER TABLE "doc_blocks" DROP CONSTRAINT "doc_blocks_parentBlockId_fkey";
ALTER TABLE "doc_chunks" DROP CONSTRAINT "doc_chunks_documentId_fkey";
ALTER TABLE "doc_chunks" DROP CONSTRAINT "doc_chunks_versionId_fkey";
ALTER TABLE "doc_chunks" DROP CONSTRAINT "doc_chunks_blockId_fkey";
ALTER TABLE "doc_source_artifacts" DROP CONSTRAINT "doc_source_artifacts_documentId_fkey";
ALTER TABLE "doc_source_artifacts" DROP CONSTRAINT "doc_source_artifacts_versionId_fkey";
ALTER TABLE "doc_conversion_runs" DROP CONSTRAINT "doc_conversion_runs_documentId_fkey";
ALTER TABLE "doc_conversion_runs" DROP CONSTRAINT "doc_conversion_runs_sourceArtifactId_fkey";
ALTER TABLE "knowledge_edges" DROP CONSTRAINT "knowledge_edges_sourceNodeId_fkey";
ALTER TABLE "knowledge_edges" DROP CONSTRAINT "knowledge_edges_targetNodeId_fkey";
ALTER TABLE "doc_entity_mentions" DROP CONSTRAINT "doc_entity_mentions_documentId_fkey";
ALTER TABLE "doc_entity_mentions" DROP CONSTRAINT "doc_entity_mentions_versionId_fkey";
ALTER TABLE "doc_entity_mentions" DROP CONSTRAINT "doc_entity_mentions_blockId_fkey";
ALTER TABLE "doc_entity_mentions" DROP CONSTRAINT "doc_entity_mentions_nodeId_fkey";
ALTER TABLE "doc_context_package_items" DROP CONSTRAINT "doc_context_package_items_contextPackageId_fkey";
ALTER TABLE "doc_context_package_items" DROP CONSTRAINT "doc_context_package_items_documentId_fkey";
ALTER TABLE "doc_context_package_items" DROP CONSTRAINT "doc_context_package_items_versionId_fkey";
ALTER TABLE "doc_context_package_items" DROP CONSTRAINT "doc_context_package_items_blockId_fkey";
ALTER TABLE "doc_export_artifacts" DROP CONSTRAINT "doc_export_artifacts_documentId_fkey";
ALTER TABLE "doc_export_artifacts" DROP CONSTRAINT "doc_export_artifacts_contextPackageId_fkey";
ALTER TABLE "doc_export_artifacts" DROP CONSTRAINT "doc_export_artifacts_versionId_fkey";
ALTER TABLE "doc_task_candidates" DROP CONSTRAINT "doc_task_candidates_documentId_fkey";
ALTER TABLE "doc_task_candidates" DROP CONSTRAINT "doc_task_candidates_blockId_fkey";
ALTER TABLE "doc_governance_candidates" DROP CONSTRAINT "doc_governance_candidates_documentId_fkey";
ALTER TABLE "doc_governance_candidates" DROP CONSTRAINT "doc_governance_candidates_blockId_fkey";

DROP INDEX "doc_document_versions_documentId_idx";
DROP INDEX "doc_conversion_runs_documentId_startedAt_idx";
DROP INDEX "knowledge_edges_sourceNodeId_idx";
DROP INDEX "knowledge_edges_targetNodeId_idx";
DROP INDEX "doc_entity_mentions_documentId_versionId_idx";
DROP INDEX "doc_entity_mentions_nodeId_idx";
DROP INDEX "doc_context_package_items_documentId_idx";
DROP INDEX "doc_task_candidates_documentId_idx";
DROP INDEX "doc_governance_candidates_documentId_idx";

CREATE UNIQUE INDEX "doc_documents_tenantId_id_key" ON "doc_documents"("tenantId", "id");
CREATE UNIQUE INDEX "doc_document_versions_tenantId_id_key" ON "doc_document_versions"("tenantId", "id");
CREATE UNIQUE INDEX "doc_blocks_tenantId_id_key" ON "doc_blocks"("tenantId", "id");
CREATE UNIQUE INDEX "doc_source_artifacts_tenantId_id_key" ON "doc_source_artifacts"("tenantId", "id");
CREATE UNIQUE INDEX "knowledge_nodes_tenantId_id_key" ON "knowledge_nodes"("tenantId", "id");
CREATE UNIQUE INDEX "doc_context_packages_tenantId_id_key" ON "doc_context_packages"("tenantId", "id");

CREATE INDEX "doc_document_versions_tenantId_documentId_idx" ON "doc_document_versions"("tenantId", "documentId");
CREATE INDEX "doc_conversion_runs_tenantId_documentId_startedAt_idx" ON "doc_conversion_runs"("tenantId", "documentId", "startedAt");
CREATE INDEX "knowledge_edges_tenantId_sourceNodeId_idx" ON "knowledge_edges"("tenantId", "sourceNodeId");
CREATE INDEX "knowledge_edges_tenantId_targetNodeId_idx" ON "knowledge_edges"("tenantId", "targetNodeId");
CREATE INDEX "doc_entity_mentions_tenantId_documentId_versionId_idx" ON "doc_entity_mentions"("tenantId", "documentId", "versionId");
CREATE INDEX "doc_entity_mentions_tenantId_nodeId_idx" ON "doc_entity_mentions"("tenantId", "nodeId");
CREATE INDEX "doc_context_package_items_tenantId_documentId_idx" ON "doc_context_package_items"("tenantId", "documentId");
CREATE INDEX "doc_task_candidates_tenantId_documentId_idx" ON "doc_task_candidates"("tenantId", "documentId");
CREATE INDEX "doc_governance_candidates_tenantId_documentId_idx" ON "doc_governance_candidates"("tenantId", "documentId");
CREATE INDEX "doc_documents_tenantId_currentVersionId_idx" ON "doc_documents"("tenantId", "currentVersionId");
CREATE INDEX "doc_blocks_tenantId_versionId_idx" ON "doc_blocks"("tenantId", "versionId");
CREATE INDEX "doc_blocks_tenantId_parentBlockId_idx" ON "doc_blocks"("tenantId", "parentBlockId");
CREATE INDEX "doc_chunks_tenantId_blockId_idx" ON "doc_chunks"("tenantId", "blockId");
CREATE INDEX "doc_source_artifacts_tenantId_documentId_idx" ON "doc_source_artifacts"("tenantId", "documentId");
CREATE INDEX "doc_source_artifacts_tenantId_versionId_idx" ON "doc_source_artifacts"("tenantId", "versionId");
CREATE INDEX "doc_conversion_runs_tenantId_sourceArtifactId_idx" ON "doc_conversion_runs"("tenantId", "sourceArtifactId");
CREATE INDEX "doc_entity_mentions_tenantId_versionId_idx" ON "doc_entity_mentions"("tenantId", "versionId");
CREATE INDEX "doc_entity_mentions_tenantId_blockId_idx" ON "doc_entity_mentions"("tenantId", "blockId");
CREATE INDEX "doc_context_package_items_tenantId_versionId_idx" ON "doc_context_package_items"("tenantId", "versionId");
CREATE INDEX "doc_context_package_items_tenantId_blockId_idx" ON "doc_context_package_items"("tenantId", "blockId");
CREATE INDEX "doc_export_artifacts_tenantId_documentId_idx" ON "doc_export_artifacts"("tenantId", "documentId");
CREATE INDEX "doc_export_artifacts_tenantId_contextPackageId_idx" ON "doc_export_artifacts"("tenantId", "contextPackageId");
CREATE INDEX "doc_export_artifacts_tenantId_versionId_idx" ON "doc_export_artifacts"("tenantId", "versionId");
CREATE INDEX "doc_task_candidates_tenantId_blockId_idx" ON "doc_task_candidates"("tenantId", "blockId");
CREATE INDEX "doc_governance_candidates_tenantId_blockId_idx" ON "doc_governance_candidates"("tenantId", "blockId");

ALTER TABLE "doc_documents" ADD CONSTRAINT "doc_documents_tenantId_currentVersionId_fkey" FOREIGN KEY ("tenantId", "currentVersionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_document_versions" ADD CONSTRAINT "doc_document_versions_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_blocks" ADD CONSTRAINT "doc_blocks_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_blocks" ADD CONSTRAINT "doc_blocks_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_blocks" ADD CONSTRAINT "doc_blocks_tenantId_parentBlockId_fkey" FOREIGN KEY ("tenantId", "parentBlockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_chunks" ADD CONSTRAINT "doc_chunks_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_chunks" ADD CONSTRAINT "doc_chunks_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_chunks" ADD CONSTRAINT "doc_chunks_tenantId_blockId_fkey" FOREIGN KEY ("tenantId", "blockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_source_artifacts" ADD CONSTRAINT "doc_source_artifacts_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_source_artifacts" ADD CONSTRAINT "doc_source_artifacts_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_conversion_runs" ADD CONSTRAINT "doc_conversion_runs_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_conversion_runs" ADD CONSTRAINT "doc_conversion_runs_tenantId_sourceArtifactId_fkey" FOREIGN KEY ("tenantId", "sourceArtifactId") REFERENCES "doc_source_artifacts"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_tenantId_sourceNodeId_fkey" FOREIGN KEY ("tenantId", "sourceNodeId") REFERENCES "knowledge_nodes"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_tenantId_targetNodeId_fkey" FOREIGN KEY ("tenantId", "targetNodeId") REFERENCES "knowledge_nodes"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_entity_mentions" ADD CONSTRAINT "doc_entity_mentions_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_entity_mentions" ADD CONSTRAINT "doc_entity_mentions_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_entity_mentions" ADD CONSTRAINT "doc_entity_mentions_tenantId_blockId_fkey" FOREIGN KEY ("tenantId", "blockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_entity_mentions" ADD CONSTRAINT "doc_entity_mentions_tenantId_nodeId_fkey" FOREIGN KEY ("tenantId", "nodeId") REFERENCES "knowledge_nodes"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_context_package_items" ADD CONSTRAINT "doc_context_package_items_tenantId_contextPackageId_fkey" FOREIGN KEY ("tenantId", "contextPackageId") REFERENCES "doc_context_packages"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_context_package_items" ADD CONSTRAINT "doc_context_package_items_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_context_package_items" ADD CONSTRAINT "doc_context_package_items_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_context_package_items" ADD CONSTRAINT "doc_context_package_items_tenantId_blockId_fkey" FOREIGN KEY ("tenantId", "blockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_export_artifacts" ADD CONSTRAINT "doc_export_artifacts_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_export_artifacts" ADD CONSTRAINT "doc_export_artifacts_tenantId_contextPackageId_fkey" FOREIGN KEY ("tenantId", "contextPackageId") REFERENCES "doc_context_packages"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_export_artifacts" ADD CONSTRAINT "doc_export_artifacts_tenantId_versionId_fkey" FOREIGN KEY ("tenantId", "versionId") REFERENCES "doc_document_versions"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_task_candidates" ADD CONSTRAINT "doc_task_candidates_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_task_candidates" ADD CONSTRAINT "doc_task_candidates_tenantId_blockId_fkey" FOREIGN KEY ("tenantId", "blockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "doc_governance_candidates" ADD CONSTRAINT "doc_governance_candidates_tenantId_documentId_fkey" FOREIGN KEY ("tenantId", "documentId") REFERENCES "doc_documents"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc_governance_candidates" ADD CONSTRAINT "doc_governance_candidates_tenantId_blockId_fkey" FOREIGN KEY ("tenantId", "blockId") REFERENCES "doc_blocks"("tenantId", "id") ON DELETE NO ACTION ON UPDATE CASCADE;
