use std::{
    collections::{BTreeSet, HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::Mutex,
};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::resources::WorkspaceResourceService;

const ENV_FILES: [&str; 6] = [
    ".env",
    ".env.local",
    ".env.development",
    ".env.staging",
    ".env.production",
    ".env.example",
];
const MAX_ENV_BYTES: usize = 256 * 1024;
const MAX_VARIABLES: usize = 256;
static ENVIRONMENT_SAVE_LOCK: Mutex<()> = Mutex::new(());

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentFile {
    pub file_name: String,
    pub size: u64,
    pub modified_at: u128,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentVariable {
    pub key: String,
    pub value: Option<String>,
    pub sensitive: bool,
    pub source: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentDocument {
    pub app_id: String,
    pub file_name: String,
    pub revision: String,
    pub variables: Vec<EnvironmentVariable>,
    pub missing_required: Vec<String>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentExport {
    pub export_id: String,
    pub file_name: String,
    pub key_count: usize,
    pub generated_count: usize,
}

pub struct EnvironmentExportStore {
    root: PathBuf,
    lock: Mutex<()>,
}

impl EnvironmentExportStore {
    pub fn at(root: PathBuf) -> Self {
        Self {
            root,
            lock: Mutex::new(()),
        }
    }

    pub fn generate(
        &self,
        resources: &WorkspaceResourceService,
        app_id: &str,
    ) -> Result<EnvironmentExport, String> {
        let _guard = self
            .lock
            .lock()
            .map_err(|_| "Environment export lock poisoned")?;
        let app_root = resources.app_root(app_id)?;
        let manifest_path = app_root.join("infrastructure.json");
        let bytes = fs::read(&manifest_path)
            .map_err(|error| format!("Infrastructure manifest is unavailable: {error}"))?;
        if bytes.len() > MAX_ENV_BYTES {
            return Err("Infrastructure manifest exceeds 256 KiB".into());
        }
        let manifest: serde_json::Value = serde_json::from_slice(&bytes)
            .map_err(|error| format!("Infrastructure manifest is invalid: {error}"))?;
        if manifest
            .get("schemaVersion")
            .and_then(|value| value.as_str())
            != Some("v1")
            || manifest.get("appId").and_then(|value| value.as_str()) != Some(app_id)
        {
            return Err("Infrastructure manifest identity is invalid".into());
        }
        let keys = manifest
            .pointer("/environment/keys")
            .and_then(|value| value.as_array())
            .ok_or("Infrastructure environment keys are invalid")?;
        if keys.len() > MAX_VARIABLES {
            return Err("Infrastructure environment has more than 256 keys".into());
        }
        let mut output = vec![
            "# Generated by Matriz Control from infrastructure.json".to_owned(),
            "# Secrets are intentionally empty and no existing .env file was read.".to_owned(),
        ];
        let mut generated_count = 0;
        for item in keys {
            let name = item
                .get("name")
                .and_then(|value| value.as_str())
                .ok_or("Infrastructure environment key has no name")?;
            validate_key(name)?;
            let secret = item
                .get("secret")
                .and_then(|value| value.as_bool())
                .unwrap_or(true);
            let source = item
                .get("source")
                .and_then(|value| value.as_str())
                .unwrap_or("unknown");
            let value = if secret {
                None
            } else {
                generated_value(name, &manifest)
            };
            if value.is_some() {
                generated_count += 1;
            }
            output.push(format!("# source={source} · secret={secret}"));
            output.push(format!("{name}={}", value.unwrap_or_default()));
        }
        fs::create_dir_all(&self.root).map_err(|error| error.to_string())?;
        let file_name = format!("{app_id}.env.generated");
        atomic_write(
            &self.root.join(&file_name),
            format!("{}\n", output.join("\n")).as_bytes(),
        )?;
        Ok(EnvironmentExport {
            export_id: app_id.into(),
            file_name,
            key_count: keys.len(),
            generated_count,
        })
    }

    pub fn reveal(&self, export_id: &str) -> Result<(), String> {
        crate::catalog::app_definition(export_id)?;
        let path = self.root.join(format!("{export_id}.env.generated"));
        let path = path
            .canonicalize()
            .map_err(|_| "Generate the environment export first".to_owned())?;
        let root = self
            .root
            .canonicalize()
            .map_err(|error| error.to_string())?;
        if !path.starts_with(&root) || path.parent() != Some(root.as_path()) {
            return Err("Environment export escaped its root".into());
        }
        Command::new("explorer.exe")
            .arg("/select,")
            .arg(path)
            .spawn()
            .map_err(|error| format!("Could not reveal environment export: {error}"))?;
        Ok(())
    }
}

fn generated_value(key: &str, manifest: &serde_json::Value) -> Option<String> {
    let port = manifest
        .pointer("/runtime/port")
        .and_then(|value| value.as_u64());
    match key {
        "PORT" => port.map(|value| value.to_string()),
        "NATS_URL" => Some("nats://127.0.0.1:54222".into()),
        "CACHE_URL" => Some("redis://127.0.0.1:46379".into()),
        "MATRIZ_IDENTITY_ISSUER" | "IDENTITY_ISSUER" => Some("http://127.0.0.1:8080".into()),
        value if value.ends_with("_OIDC_CLIENT_ID") => manifest
            .pointer("/identity/oidcClientId")
            .and_then(|value| value.as_str())
            .map(str::to_owned),
        value if value.ends_with("_OIDC_CALLBACK_URL") => Some(format!(
            "http://127.0.0.1:{}{}",
            port?,
            manifest.pointer("/identity/callbackPath")?.as_str()?
        )),
        value if value.ends_with("_OUTBOX_WORKER_ENABLED") => Some("true".into()),
        value if value.ends_with("_CACHE_DEFAULT_TTL_SECONDS") => manifest
            .pointer("/cache/defaultTtlSeconds")
            .and_then(|value| value.as_u64())
            .map(|value| value.to_string()),
        _ => None,
    }
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentVariableInput {
    pub key: String,
    pub value: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentSaveRequest {
    pub app_id: String,
    pub file_name: String,
    pub revision: String,
    pub variables: Vec<EnvironmentVariableInput>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentComparisonEntry {
    pub key: String,
    pub sensitive: bool,
    pub status: &'static str,
    pub source_value: Option<String>,
    pub target_value: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentComparison {
    pub app_id: String,
    pub source_file: String,
    pub target_file: String,
    pub target_revision: String,
    pub entries: Vec<EnvironmentComparisonEntry>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentPromotionRequest {
    pub app_id: String,
    pub source_file: String,
    pub target_file: String,
    pub target_revision: String,
    pub keys: Vec<String>,
}

#[derive(Clone, Debug)]
enum EnvLine {
    Variable { key: String, value: String },
    Raw(String),
}

pub struct EnvironmentService {
    resources: WorkspaceResourceService,
}

impl EnvironmentService {
    pub fn new(resources: WorkspaceResourceService) -> Self {
        Self { resources }
    }

    pub fn list(&self, app_id: &str) -> Result<Vec<EnvironmentFile>, String> {
        let root = self.resources.app_root(app_id)?;
        let mut files = Vec::new();
        for file_name in ENV_FILES {
            let path = root.join(file_name);
            if !path.is_file() {
                continue;
            }
            let metadata = fs::metadata(&path).map_err(|error| error.to_string())?;
            files.push(EnvironmentFile {
                file_name: file_name.into(),
                size: metadata.len(),
                modified_at: metadata
                    .modified()
                    .ok()
                    .and_then(|time| time.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|duration| duration.as_millis())
                    .unwrap_or_default(),
            });
        }
        Ok(files)
    }

    pub fn read(&self, app_id: &str, file_name: &str) -> Result<EnvironmentDocument, String> {
        validate_env_file(file_name)?;
        let path = self.resources.existing_path(app_id, file_name)?;
        let contents = read_bounded(&path)?;
        let lines = parse(&contents)?;
        let variables = lines
            .iter()
            .filter_map(|line| match line {
                EnvLine::Variable { key, value } => Some(EnvironmentVariable {
                    key: key.clone(),
                    value: (!is_sensitive(key)).then(|| value.clone()),
                    sensitive: is_sensitive(key),
                    source: file_name.into(),
                }),
                EnvLine::Raw(_) => None,
            })
            .collect::<Vec<_>>();
        if variables.len() > MAX_VARIABLES {
            return Err("Environment has more than 256 variables".into());
        }
        let keys = variables
            .iter()
            .map(|item| item.key.as_str())
            .collect::<HashSet<_>>();
        let missing_required = self
            .required_keys(app_id)?
            .into_iter()
            .filter(|key| !keys.contains(key.as_str()))
            .collect();
        Ok(EnvironmentDocument {
            app_id: app_id.into(),
            file_name: file_name.into(),
            revision: revision(&contents),
            variables,
            missing_required,
        })
    }

    pub fn reveal(&self, app_id: &str, file_name: &str, key: &str) -> Result<String, String> {
        validate_env_file(file_name)?;
        validate_key(key)?;
        if !is_sensitive(key) {
            return Err("Only sensitive values require explicit reveal".into());
        }
        let contents = read_bounded(&self.resources.existing_path(app_id, file_name)?)?;
        parse(&contents)?
            .into_iter()
            .find_map(|line| match line {
                EnvLine::Variable {
                    key: candidate,
                    value,
                } if candidate == key => Some(value),
                _ => None,
            })
            .ok_or_else(|| "Environment variable was not found".into())
    }

    pub fn compare(
        &self,
        app_id: &str,
        source_file: &str,
        target_file: &str,
    ) -> Result<EnvironmentComparison, String> {
        validate_env_file(source_file)?;
        validate_env_file(target_file)?;
        if source_file == target_file {
            return Err("Choose two different environment files".into());
        }
        let source_contents = read_bounded(&self.resources.existing_path(app_id, source_file)?)?;
        let target_contents = read_bounded(&self.resources.existing_path(app_id, target_file)?)?;
        let source = variable_map(&parse(&source_contents)?);
        let target = variable_map(&parse(&target_contents)?);
        let keys = source
            .keys()
            .chain(target.keys())
            .cloned()
            .collect::<BTreeSet<_>>();
        let entries = keys
            .into_iter()
            .map(|key| {
                let source_value = source.get(&key);
                let target_value = target.get(&key);
                let sensitive = is_sensitive(&key);
                EnvironmentComparisonEntry {
                    key,
                    sensitive,
                    status: match (source_value, target_value) {
                        (None, Some(_)) => "missingSource",
                        (Some(_), None) => "missingTarget",
                        (Some(left), Some(right)) if left == right => "equal",
                        _ => "different",
                    },
                    source_value: (!sensitive).then(|| source_value.cloned()).flatten(),
                    target_value: (!sensitive).then(|| target_value.cloned()).flatten(),
                }
            })
            .collect();
        Ok(EnvironmentComparison {
            app_id: app_id.into(),
            source_file: source_file.into(),
            target_file: target_file.into(),
            target_revision: revision(&target_contents),
            entries,
        })
    }

    pub fn promote(
        &self,
        request: EnvironmentPromotionRequest,
    ) -> Result<EnvironmentDocument, String> {
        let _save_guard = ENVIRONMENT_SAVE_LOCK
            .lock()
            .map_err(|_| "Environment save lock poisoned")?;
        validate_env_file(&request.source_file)?;
        validate_env_file(&request.target_file)?;
        if request.source_file == request.target_file {
            return Err("Source and target environments must be different".into());
        }
        if request.keys.is_empty() || request.keys.len() > MAX_VARIABLES {
            return Err("Select between 1 and 256 environment keys".into());
        }
        let source_path = self
            .resources
            .existing_path(&request.app_id, &request.source_file)?;
        let target_path = self
            .resources
            .existing_path(&request.app_id, &request.target_file)?;
        let source_contents = read_bounded(&source_path)?;
        let target_contents = read_bounded(&target_path)?;
        if revision(&target_contents) != request.target_revision {
            return Err("Target environment changed on disk; compare again".into());
        }
        let source = variable_map(&parse(&source_contents)?);
        let target_lines = parse(&target_contents)?;
        let mut values = variable_map(&target_lines);
        let mut selected = HashSet::new();
        for key in request.keys {
            validate_key(&key)?;
            if !selected.insert(key.clone()) {
                return Err("Environment promotion keys must be unique".into());
            }
            let value = source
                .get(&key)
                .cloned()
                .ok_or_else(|| format!("{key} does not exist in the source environment"))?;
            values.insert(key, value);
        }
        let mut written = HashSet::new();
        let mut output = Vec::new();
        for line in target_lines {
            match line {
                EnvLine::Raw(raw) => output.push(raw),
                EnvLine::Variable { key, .. } => {
                    output.push(format!(
                        "{key}={}",
                        values.get(&key).cloned().unwrap_or_default()
                    ));
                    written.insert(key);
                }
            }
        }
        for key in selected {
            if !written.contains(&key) {
                output.push(format!(
                    "{key}={}",
                    values.get(&key).cloned().unwrap_or_default()
                ));
            }
        }
        let mut contents = output.join("\n");
        if target_contents.ends_with('\n') || !contents.is_empty() {
            contents.push('\n');
        }
        if contents.len() > MAX_ENV_BYTES {
            return Err("Environment exceeds 256 KiB".into());
        }
        atomic_write(&target_path, contents.as_bytes())?;
        self.read(&request.app_id, &request.target_file)
    }

    pub fn save(&self, request: EnvironmentSaveRequest) -> Result<EnvironmentDocument, String> {
        let _save_guard = ENVIRONMENT_SAVE_LOCK
            .lock()
            .map_err(|_| "Environment save lock poisoned")?;
        validate_env_file(&request.file_name)?;
        if request.variables.len() > MAX_VARIABLES {
            return Err("Environment has more than 256 variables".into());
        }
        let path = self
            .resources
            .existing_path(&request.app_id, &request.file_name)?;
        let current = read_bounded(&path)?;
        if revision(&current) != request.revision {
            return Err("Environment changed on disk; reload before saving".into());
        }
        let original = parse(&current)?;
        let existing = original
            .iter()
            .filter_map(|line| match line {
                EnvLine::Variable { key, value } => Some((key.clone(), value.clone())),
                _ => None,
            })
            .collect::<HashMap<_, _>>();
        let mut requested = HashMap::new();
        let mut order = Vec::new();
        for input in request.variables {
            validate_key(&input.key)?;
            if input
                .value
                .as_deref()
                .is_some_and(|value| value.contains(['\n', '\r', '\0']))
            {
                return Err("Environment values cannot contain control newlines".into());
            }
            if requested.insert(input.key.clone(), input.value).is_some() {
                return Err("Environment keys must be unique".into());
            }
            order.push(input.key);
        }
        let mut written = HashSet::new();
        let mut output = Vec::new();
        for line in original {
            match line {
                EnvLine::Raw(raw) => output.push(raw),
                EnvLine::Variable { key, .. } if requested.contains_key(&key) => {
                    let value = requested
                        .get(&key)
                        .and_then(Clone::clone)
                        .or_else(|| existing.get(&key).cloned())
                        .unwrap_or_default();
                    output.push(format!("{key}={value}"));
                    written.insert(key);
                }
                EnvLine::Variable { .. } => {}
            }
        }
        for key in order {
            if written.contains(&key) {
                continue;
            }
            let value = requested.remove(&key).flatten().unwrap_or_default();
            output.push(format!("{key}={value}"));
        }
        let mut contents = output.join("\n");
        if current.ends_with('\n') || !contents.is_empty() {
            contents.push('\n');
        }
        if contents.len() > MAX_ENV_BYTES {
            return Err("Environment exceeds 256 KiB".into());
        }
        atomic_write(&path, contents.as_bytes())?;
        self.read(&request.app_id, &request.file_name)
    }

    fn required_keys(&self, app_id: &str) -> Result<Vec<String>, String> {
        let path = self.resources.app_root(app_id)?.join(".env.example");
        if !path.is_file() {
            return Ok(Vec::new());
        }
        Ok(parse(&read_bounded(&path)?)?
            .into_iter()
            .filter_map(|line| match line {
                EnvLine::Variable { key, .. } => Some(key),
                _ => None,
            })
            .collect())
    }
}

fn variable_map(lines: &[EnvLine]) -> HashMap<String, String> {
    lines
        .iter()
        .filter_map(|line| match line {
            EnvLine::Variable { key, value } => Some((key.clone(), value.clone())),
            EnvLine::Raw(_) => None,
        })
        .collect()
}

fn validate_env_file(file_name: &str) -> Result<(), String> {
    if ENV_FILES.contains(&file_name) {
        Ok(())
    } else {
        Err("Unsupported environment filename".into())
    }
}

fn validate_key(key: &str) -> Result<(), String> {
    let mut chars = key.chars();
    if !chars
        .next()
        .is_some_and(|c| c == '_' || c.is_ascii_alphabetic())
        || !chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
    {
        return Err("Invalid environment variable key".into());
    }
    Ok(())
}

fn is_sensitive(key: &str) -> bool {
    let upper = key.to_ascii_uppercase();
    !matches!(
        upper.as_str(),
        "PORT" | "NODE_ENV" | "APP_ENV" | "ENVIRONMENT" | "HOST" | "LOG_LEVEL"
    ) && !upper.starts_with("NEXT_PUBLIC_")
        && !upper.starts_with("VITE_")
        && !upper.starts_with("PUBLIC_")
}

fn parse(contents: &str) -> Result<Vec<EnvLine>, String> {
    contents
        .lines()
        .map(|line| {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                return Ok(EnvLine::Raw(line.into()));
            }
            let candidate = trimmed.strip_prefix("export ").unwrap_or(trimmed);
            let (key, value) = candidate
                .split_once('=')
                .ok_or("Invalid environment line")?;
            validate_key(key.trim())?;
            Ok(EnvLine::Variable {
                key: key.trim().into(),
                value: value.into(),
            })
        })
        .collect()
}

fn read_bounded(path: &Path) -> Result<String, String> {
    let metadata = fs::metadata(path).map_err(|error| error.to_string())?;
    if metadata.len() > MAX_ENV_BYTES as u64 {
        return Err("Environment exceeds 256 KiB".into());
    }
    fs::read_to_string(path).map_err(|error| format!("Environment must be UTF-8: {error}"))
}

fn revision(contents: &str) -> String {
    format!("{:x}", Sha256::digest(contents.as_bytes()))
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or("Environment path has no filename")?;
    let temporary = path.with_file_name(format!(".{file_name}.{}.tmp", uuid::Uuid::new_v4()));
    fs::write(&temporary, bytes).map_err(|error| error.to_string())?;
    fs::rename(&temporary, path).map_err(|error| {
        let _ = fs::remove_file(&temporary);
        error.to_string()
    })
}
