import {
  authorityLevelSchema,
  humanReviewerSchema,
  missionEvidenceInputSchema,
  missionStatusSchema,
  safeRelativePathSchema,
  type Mission,
  type MissionEvidenceInput,
  type ReviewMissionInput,
} from "../domain/agent-operations"
import type {
  CreateTeamHandoffInput,
  CreateTeamMissionInput,
  CreateTeamProfileInput,
} from "./agent-team-service"

type AgentTeamFormKind = "profile" | "mission" | "evidence" | "handoff" | "review" | "transition"

type MissionReference = { projectId: string; missionId: string; revision: string }
type ProfileForm = { projectId: string; input: CreateTeamProfileInput }
type MissionForm = { projectId: string; input: CreateTeamMissionInput }
type EvidenceForm = MissionReference & { input: MissionEvidenceInput }
type HandoffForm = MissionReference & { input: CreateTeamHandoffInput }
type ReviewForm = MissionReference & { input: ReviewMissionInput }
type TransitionForm = MissionReference & { target: Mission["status"] }

function required(formData: FormData, key: string): string {
  const value = formData.get(key)
  if (typeof value !== "string" || !value.trim()) throw new Error(`Campo obrigatório: ${key}`)
  return value.trim()
}

function lines(formData: FormData, key: string): string[] {
  return String(formData.get(key) ?? "")
    .split("\n")
    .map((value) => value.trim())
    .filter(Boolean)
}

function projectAndMission(formData: FormData) {
  return {
    projectId: required(formData, "projectId"),
    missionId: required(formData, "missionId"),
    revision: required(formData, "revision"),
  }
}

export function parseAgentTeamForm(kind: "profile", formData: FormData): ProfileForm
export function parseAgentTeamForm(kind: "mission", formData: FormData): MissionForm
export function parseAgentTeamForm(kind: "evidence", formData: FormData): EvidenceForm
export function parseAgentTeamForm(kind: "handoff", formData: FormData): HandoffForm
export function parseAgentTeamForm(kind: "review", formData: FormData): ReviewForm
export function parseAgentTeamForm(kind: "transition", formData: FormData): TransitionForm
export function parseAgentTeamForm(
  kind: AgentTeamFormKind,
  formData: FormData,
): ProfileForm | MissionForm | EvidenceForm | HandoffForm | ReviewForm | TransitionForm {
  if (kind === "profile") {
    return {
      projectId: required(formData, "projectId"),
      input: {
        id: required(formData, "id"),
        displayName: required(formData, "displayName"),
        personaSummary: required(formData, "personaSummary"),
        missionStatement: required(formData, "missionStatement"),
        capabilityIds: lines(formData, "capabilityIds"),
        defaultAuthority: authorityLevelSchema.parse(required(formData, "defaultAuthority")),
        humanOwner: required(formData, "humanOwner"),
      },
    }
  }
  if (kind === "mission") {
    return {
      projectId: required(formData, "projectId"),
      input: {
        profileId: required(formData, "profileId"),
        title: required(formData, "title"),
        objective: required(formData, "objective"),
        allowedPaths: lines(formData, "allowedPaths").map((path) => safeRelativePathSchema.parse(path)),
        authority: authorityLevelSchema.parse(required(formData, "authority")),
        contextReferences: lines(formData, "contextReferences"),
        acceptanceCriteria: lines(formData, "acceptanceCriteria"),
      },
    }
  }
  if (kind === "evidence") {
    const base = projectAndMission(formData)
    const evidence = missionEvidenceInputSchema.parse({
      // Evidence IDs are generated by the server action.  The placeholder only
      // lets the domain schema validate the remaining, renderer-supplied shape.
      id: "evidence_00000000-0000-4000-8000-000000000000",
      kind: required(formData, "kind"),
      summary: required(formData, "summary"),
      recordedBy: required(formData, "recordedBy"),
      ...(formData.get("kind") === "file" ? { path: required(formData, "reference") } : {}),
      ...(formData.get("kind") === "test" ? { command: required(formData, "reference") } : {}),
      ...(formData.get("kind") === "url" ? { url: required(formData, "reference") } : {}),
      ...(formData.get("kind") === "note" ? { note: required(formData, "reference") } : {}),
    })
    return { ...base, input: evidence }
  }
  if (kind === "handoff") {
    return {
      ...projectAndMission(formData),
      input: {
        contextSummary: required(formData, "contextSummary"),
        decisions: lines(formData, "decisions"),
        risks: lines(formData, "risks"),
        nextStep: required(formData, "nextStep"),
        authoredBy: humanReviewerSchema.parse({ kind: "human", id: required(formData, "reviewerId") }),
      },
    }
  }
  if (kind === "review") {
    const decision = required(formData, "decision")
    if (decision !== "approved" && decision !== "changes_requested") {
      throw new Error("Decisão de revisão inválida.")
    }
    return {
      ...projectAndMission(formData),
      input: {
        decision,
        reviewer: humanReviewerSchema.parse({ kind: "human", id: required(formData, "reviewerId") }),
        note: required(formData, "note"),
      },
    }
  }
  return {
    ...projectAndMission(formData),
    target: missionStatusSchema.parse(required(formData, "target")),
  }
}
