[package]
name = "matriz-admin-desktop"
version = "0.1.0"
description = "Matriz Admin native operations app"
edition = "2021"

[lib]
name = "matriz_admin_desktop_native"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
