"use client"
import { useEffect, useState } from "react"
import type { DoctorViewModel } from "./doctor-presenter"
export function DoctorPage() {
  const [data, setData] = useState<DoctorViewModel | null>(null); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState<{ token: string; label: string } | null>(null)
  const load = (refresh = false) => fetch(`/api/doctor${refresh ? "?refresh=1" : ""}`).then(async (response) => { if (!response.ok) throw new Error("Falha no diagnóstico"); setData(await response.json() as DoctorViewModel) }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Falha no diagnóstico"))
  useEffect(() => { void load() }, [])
  async function request(projectId: string, targetId: string, label: string) { const response = await fetch("/api/doctor/cleanup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, targetId }) }); const body = await response.json() as { token?: string; error?: string }; if (!response.ok || !body.token) return setError(body.error ?? "Falha na prévia"); setPreview({ token: body.token, label }) }
  async function confirm() { if (!preview) return; const response = await fetch("/api/doctor/cleanup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: preview.token }) }); if (!response.ok) { const body = await response.json() as { error?: string }; setError(body.error ?? "Falha na limpeza") } setPreview(null); await load(true) }
  return <main className="page"><div className="page-title"><span className="section-label">SAÚDE / RECURSOS</span><h1>Doctor</h1><p>Disco, cache e memória por projeto conhecido.</p></div>{error ? <p role="alert">{error}</p> : null}{data ? <><section className={`doctor-summary status-${data.drive.status}`}><span>unidade</span><strong>{data.drive.free} livres</strong><small>{data.drive.total} totais · {data.drive.statusLabel}</small><button onClick={() => void load(true)}>Atualizar</button></section><section className="doctor-grid">{data.projects.map((project) => <article className={`doctor-card status-${project.status}`} key={project.id}><header><span><strong>{project.name}</strong><small>{project.route}</small></span><b>{project.statusLabel}</b></header><dl><div><dt>projeto</dt><dd>{project.total}</dd></div><div><dt>cache</dt><dd>{project.cache}</dd></div><div><dt>ram</dt><dd>{project.memory}</dd></div></dl><footer>{project.cacheTargets.filter((target) => target.bytes > 0).map((target) => <button key={target.id} onClick={() => void request(project.id, target.id, `${project.name} / ${target.id} / ${target.size}`)}>Limpar {target.id} · {target.size}</button>)}</footer></article>)}</section></> : <p className="muted">Coletando diagnóstico…</p>}{preview ? <div className="confirm-overlay" role="dialog" aria-modal="true" aria-label="Confirmar limpeza"><div><h2>Confirmar limpeza regenerável</h2><p>{preview.label}</p><button onClick={() => setPreview(null)}>Cancelar</button><button className="primary" onClick={() => void confirm()}>Confirmar limpeza</button></div></div> : null}</main>
}
