CREATE TYPE "CommerceOrderStatus" AS ENUM ('PLACED', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED');
CREATE TYPE "DemoPaymentStatus" AS ENUM ('SIMULATED_APPROVED', 'SIMULATED_REFUNDED');
CREATE TYPE "CommerceOrderChannel" AS ENUM ('DEMO_STOREFRONT', 'MANUAL');
CREATE TYPE "FulfillmentType" AS ENUM ('PICKUP');

CREATE TABLE "store_publications" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "companyId" TEXT NOT NULL, "storeSlug" TEXT NOT NULL, "displayName" TEXT NOT NULL, "description" TEXT, "isPublished" BOOLEAN NOT NULL DEFAULT false, "version" INTEGER NOT NULL DEFAULT 1, "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "store_publications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "customers" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "normalizedEmail" TEXT, "normalizedPhone" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "customers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "commerce_orders" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "orderNumber" INTEGER NOT NULL, "status" "CommerceOrderStatus" NOT NULL DEFAULT 'PLACED', "paymentStatus" "DemoPaymentStatus" NOT NULL DEFAULT 'SIMULATED_APPROVED', "channel" "CommerceOrderChannel" NOT NULL DEFAULT 'DEMO_STOREFRONT', "fulfillmentType" "FulfillmentType" NOT NULL DEFAULT 'PICKUP', "subtotalCents" INTEGER NOT NULL, "totalCents" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'BRL', "idempotencyKey" TEXT NOT NULL, "commandHash" TEXT NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "commerce_orders_pkey" PRIMARY KEY ("id"));
CREATE TABLE "order_items" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "orderId" TEXT NOT NULL, "variantId" TEXT NOT NULL, "productNameSnapshot" TEXT NOT NULL, "variantNameSnapshot" TEXT NOT NULL, "unitPriceCents" INTEGER NOT NULL, "quantity" INTEGER NOT NULL, "totalCents" INTEGER NOT NULL, "recipeVersionSnapshot" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "order_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "order_timeline_events" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "orderId" TEXT NOT NULL, "status" "CommerceOrderStatus" NOT NULL, "actorType" TEXT NOT NULL, "actorId" TEXT, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "order_timeline_events_pkey" PRIMARY KEY ("id"));
CREATE TABLE "order_stock_consumptions" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "orderItemId" TEXT NOT NULL, "ingredientId" TEXT NOT NULL, "movementId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "order_stock_consumptions_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "companies_tenantId_id_key" ON "companies"("tenantId", "id"); CREATE UNIQUE INDEX "ingredient_stock_movements_tenantId_id_key" ON "ingredient_stock_movements"("tenantId", "id");
CREATE UNIQUE INDEX "store_publications_tenantId_key" ON "store_publications"("tenantId"); CREATE UNIQUE INDEX "store_publications_companyId_key" ON "store_publications"("companyId"); CREATE UNIQUE INDEX "store_publications_storeSlug_key" ON "store_publications"("storeSlug"); CREATE UNIQUE INDEX "store_publications_tenantId_companyId_key" ON "store_publications"("tenantId", "companyId"); CREATE INDEX "store_publications_storeSlug_isPublished_idx" ON "store_publications"("storeSlug", "isPublished");
CREATE UNIQUE INDEX "customers_tenantId_id_key" ON "customers"("tenantId", "id"); CREATE UNIQUE INDEX "customers_tenantId_normalizedEmail_key" ON "customers"("tenantId", "normalizedEmail"); CREATE UNIQUE INDEX "customers_tenantId_normalizedPhone_key" ON "customers"("tenantId", "normalizedPhone"); CREATE INDEX "customers_tenantId_name_idx" ON "customers"("tenantId", "name");
CREATE UNIQUE INDEX "commerce_orders_tenantId_id_key" ON "commerce_orders"("tenantId", "id"); CREATE UNIQUE INDEX "commerce_orders_tenantId_orderNumber_key" ON "commerce_orders"("tenantId", "orderNumber"); CREATE UNIQUE INDEX "commerce_orders_tenantId_idempotencyKey_key" ON "commerce_orders"("tenantId", "idempotencyKey"); CREATE INDEX "commerce_orders_tenantId_status_createdAt_idx" ON "commerce_orders"("tenantId", "status", "createdAt"); CREATE INDEX "commerce_orders_tenantId_customerId_createdAt_idx" ON "commerce_orders"("tenantId", "customerId", "createdAt");
CREATE UNIQUE INDEX "order_items_tenantId_id_key" ON "order_items"("tenantId", "id"); CREATE INDEX "order_items_tenantId_orderId_idx" ON "order_items"("tenantId", "orderId"); CREATE INDEX "order_items_tenantId_variantId_idx" ON "order_items"("tenantId", "variantId"); CREATE INDEX "order_timeline_events_tenantId_orderId_createdAt_idx" ON "order_timeline_events"("tenantId", "orderId", "createdAt"); CREATE UNIQUE INDEX "order_stock_consumptions_movementId_key" ON "order_stock_consumptions"("movementId"); CREATE UNIQUE INDEX "order_stock_consumptions_tenantId_movementId_key" ON "order_stock_consumptions"("tenantId", "movementId"); CREATE UNIQUE INDEX "order_stock_consumptions_tenantId_orderItemId_ingredientId_key" ON "order_stock_consumptions"("tenantId", "orderItemId", "ingredientId"); CREATE INDEX "order_stock_consumptions_tenantId_ingredientId_createdAt_idx" ON "order_stock_consumptions"("tenantId", "ingredientId", "createdAt");

ALTER TABLE "store_publications" ADD CONSTRAINT "store_publications_tenantId_companyId_fkey" FOREIGN KEY ("tenantId", "companyId") REFERENCES "companies"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "commerce_orders" ADD CONSTRAINT "commerce_orders_tenantId_customerId_fkey" FOREIGN KEY ("tenantId", "customerId") REFERENCES "customers"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_tenantId_orderId_fkey" FOREIGN KEY ("tenantId", "orderId") REFERENCES "commerce_orders"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_tenantId_variantId_fkey" FOREIGN KEY ("tenantId", "variantId") REFERENCES "product_variants"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_timeline_events" ADD CONSTRAINT "order_timeline_events_tenantId_orderId_fkey" FOREIGN KEY ("tenantId", "orderId") REFERENCES "commerce_orders"("tenantId", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order_stock_consumptions" ADD CONSTRAINT "order_stock_consumptions_tenantId_orderItemId_fkey" FOREIGN KEY ("tenantId", "orderItemId") REFERENCES "order_items"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_stock_consumptions" ADD CONSTRAINT "order_stock_consumptions_tenantId_ingredientId_fkey" FOREIGN KEY ("tenantId", "ingredientId") REFERENCES "ingredients"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_stock_consumptions" ADD CONSTRAINT "order_stock_consumptions_tenantId_movementId_fkey" FOREIGN KEY ("tenantId", "movementId") REFERENCES "ingredient_stock_movements"("tenantId", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "commerce_orders" ADD CONSTRAINT "commerce_orders_money_check" CHECK ("subtotalCents" >= 0 AND "totalCents" >= 0 AND "orderNumber" > 0);
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_values_check" CHECK ("unitPriceCents" >= 0 AND "quantity" > 0 AND "totalCents" >= 0 AND "recipeVersionSnapshot" > 0);
ALTER TABLE "order_stock_consumptions" ADD CONSTRAINT "order_stock_consumptions_quantity_check" CHECK ("quantity" > 0);
